/* ─── PayWatch Schuldhulp City Pages ─── */
/* Unique content per city — Dutch first, natural tone, no em dashes */

export interface CityFAQ {
  question: string;
  answer: string;
}

export interface CityOrg {
  name: string;
  url: string;
  type: string;
  description: string;
  phone?: string;
}

export interface CityTip {
  title: string;
  description: string;
  icon: string; // Lucide icon name
  url?: string; // Direct link for this specific tip
}

export interface CityPage {
  slug: string;
  name: string;
  province: string;
  population: string;
  accentColor: string;       // CSS hex for city branding
  accentColorLight: string;  // Light version for backgrounds
  accentColorName: string;   // Human readable
  unsplashQuery: string;     // Search query for hero image
  unsplashQueryOrgs: string; // Search query for organizations section
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  introTitle: string;
  introText: string;
  debtContext: string;        // City-specific debt context paragraph
  localSituation: string;    // How debt affects this city specifically
  organizations: CityOrg[];
  faq: CityFAQ[];
  tips: CityTip[];
  statsHighlight: string;    // One notable stat
  ctaText: string;
  gemeenteUrl: string;       // Official gemeente schuldhulp page
  coordinates: { lat: number; lng: number };
  logoDomain: string;  // e.g. "amsterdam.nl" for logo.dev
  debtPercentage: number; // Percentage of households with problematic debt (for comparison chart)
}

export const CITY_SLUGS = [
  "rotterdam",
  "amsterdam",
  "den-haag",
  "utrecht",
  "eindhoven",
  "groningen",
  "tilburg",
  "almere",
  "breda",
  "nijmegen",
  "arnhem",
  "haarlem",
  "enschede",
  "zaanstad",
  "amersfoort",
  "apeldoorn",
  "leiden",
  "dordrecht",
  "maastricht",
  "s-hertogenbosch",
] as const;

export type CitySlug = (typeof CITY_SLUGS)[number];

export const cityPages: Record<CitySlug, CityPage> = {
  rotterdam: {
    slug: "rotterdam",
    name: "Rotterdam",
    province: "Zuid-Holland",
    population: "660.000+",
    accentColor: "#009B3A",
    accentColorLight: "#E6F7EE",
    accentColorName: "Rotterdams groen",
    unsplashQuery: "Rotterdam Netherlands skyline Erasmus bridge",
    unsplashQueryOrgs: "Rotterdam city Netherlands architecture",
    metaTitle: "Schuldhulp Rotterdam — Gratis hulp bij schulden in Rotterdam",
    metaDescription: "Heb je schulden in Rotterdam? Ontdek welke gratis hulporganisaties er zijn, hoe schuldhulpverlening werkt en wat PayWatch voor je kan doen. Bekijk lokale tips en veelgestelde vragen.",
    heroTitle: "Schuldhulp in Rotterdam",
    heroSubtitle: "Overzicht van alle hulp bij schulden in de Maasstad",
    introTitle: "Schulden in Rotterdam: je staat er niet alleen voor",
    introText: "Rotterdam is een stad van doeners. Maar ook doeners kunnen vastlopen op onverwachte rekeningen, hoge energiekosten of een plotseling inkomensverlies. In Rotterdam hebben naar schatting 1 op de 5 huishoudens te maken met problematische schulden. Dat is niet iets om je voor te schamen. De gemeente Rotterdam en diverse organisaties bieden gratis ondersteuning om je weer op weg te helpen.",
    debtContext: "Als havenstad met een diverse bevolking kent Rotterdam relatief veel huishoudens met een laag inkomen. De combinatie van stijgende huurprijzen in wijken als Feijenoord, Charlois en Delfshaven, oplopende energiekosten en de nasleep van de coronacrisis heeft ervoor gezorgd dat steeds meer Rotterdammers met betalingsachterstanden kampen. Vooral zzp'ers en flexwerkers in de haven- en dienstensector worden hard geraakt.",
    localSituation: "Rotterdam zet sterk in op vroegsignalering. Dat betekent dat de gemeente actief signalen oppikt van nutsbedrijven, zorgverzekeraars en woningcorporaties wanneer bewoners betalingsachterstanden oplopen. Je kunt dus al hulp aangeboden krijgen voordat je er zelf om vraagt. Dit is uniek in Nederland en maakt Rotterdam een voorloper op het gebied van schuldhulpverlening.",
    statsHighlight: "Ongeveer 1 op de 5 Rotterdamse huishoudens heeft problematische schulden",
    organizations: [
      {
        name: "Kredietbank Rotterdam",
        url: "https://www.rotterdam.nl/schuldhulpverlening-aanvragen",
        type: "Gemeentelijke kredietbank",
        description: "De Kredietbank Rotterdam is onderdeel van de gemeente en biedt gratis schuldhulpverlening. Ze helpen met budgetcoaching, schuldregelingen en schuldsanering. Aanmelden kan via de wijkteams of direct bij de gemeente.",
        phone: "14 010",
      },
      {
        name: "Wijkteams Rotterdam",
        url: "https://www.rotterdam.nl/wijkteams",
        type: "Wijkteam / eerste aanspreekpunt",
        description: "Elk Rotterdams wijkteam heeft medewerkers die je kunnen helpen met geldzorgen. Ze kijken samen met jou naar je situatie en verwijzen je door naar de juiste hulp. Laagdrempelig en gratis.",
        phone: "14 010",
      },
      {
        name: "SchuldHulpMaatje Rotterdam",
        url: "https://schuldhulpmaatje.nl/rotterdam/",
        type: "Vrijwillige schuldhulp",
        description: "Vrijwilligers die naast je staan bij het op orde brengen van je administratie en financien. Ze gaan mee naar gesprekken met schuldeisers en helpen je bij het aanvragen van toeslagen of regelingen.",
      },
      {
        name: "Humanitas Rotterdam",
        url: "https://www.stichtinghumanitas.nl/",
        type: "Maatschappelijke ondersteuning",
        description: "Biedt thuisadministratie, budgetmaatjes en ondersteuning bij het ordenen van je papierwerk. Vooral geschikt als je moeite hebt met de administratieve kant van je financien.",
      },
    ],
    faq: [
      {
        question: "Hoe vraag ik schuldhulpverlening aan in Rotterdam?",
        answer: "Je kunt schuldhulpverlening aanvragen door te bellen naar 14 010 of door langs te gaan bij je wijkteam. Je kunt ook online een aanvraag doen via rotterdam.nl/schuldhulpverlening-aanvragen. Er wordt dan een intakegesprek gepland waarin je situatie in kaart wordt gebracht.",
      },
      {
        question: "Is schuldhulpverlening in Rotterdam gratis?",
        answer: "Ja, schuldhulpverlening via de gemeente Rotterdam is volledig gratis. Je hoeft er niets voor te betalen. Pas op voor commerciele partijen die geld vragen voor schuldhulp. Ga altijd eerst naar de gemeente.",
      },
      {
        question: "Hoe lang duurt een schuldhulptraject in Rotterdam?",
        answer: "Een schuldhulptraject duurt gemiddeld 18 tot 36 maanden, afhankelijk van je situatie. Bij een minnelijke schuldregeling proberen ze binnen 120 dagen een akkoord te bereiken met je schuldeisers. Een wettelijke schuldsanering (WSNP) duurt standaard 18 maanden.",
      },
      {
        question: "Wat doet het vroegsignaleringsproject van Rotterdam?",
        answer: "Rotterdam krijgt signalen van energieleveranciers, zorgverzekeraars en woningcorporaties als je betalingsachterstanden hebt. De gemeente neemt dan proactief contact met je op om hulp aan te bieden, nog voordat de situatie escaleert. Je kunt dit ook weigeren, het is vrijblijvend.",
      },
      {
        question: "Kan ik hulp krijgen als ik in de Bijstand zit?",
        answer: "Zeker. Juist als je een bijstandsuitkering ontvangt, heb je recht op schuldhulpverlening. De gemeente kan daarnaast helpen met bijzondere bijstand voor onverwachte kosten of het kwijtschelden van gemeentelijke belastingen.",
      },
      {
        question: "Wat als ik al een deurwaarder aan de deur heb gehad?",
        answer: "Ook dan kun je nog hulp krijgen. Neem zo snel mogelijk contact op met het wijkteam of bel 14 010. Hoe eerder je hulp zoekt, hoe meer opties er zijn. Een deurwaarder betekent niet dat alles verloren is.",
      },
    ],
    tips: [
      {
        title: "Kwijtschelding gemeentelijke belastingen",
        description: "Als je een laag inkomen hebt, kun je in Rotterdam kwijtschelding aanvragen voor gemeentelijke belastingen en de waterschapsbelasting. Dit kan je honderden euros per jaar schelen.",
        icon: "BadgePercent",
        url: "https://www.rotterdam.nl/kwijtschelding-afvalstoffenheffing-aanvragen",
      },
      {
        title: "Rotterdampas",
        description: "Met de Rotterdampas (gratis bij laag inkomen) krijg je korting op sport, cultuur en uitjes. Het bespaart je geld op activiteiten die anders duur zouden zijn.",
        icon: "Ticket",
        url: "https://www.rotterdampas.nl/",
      },
      {
        title: "Energietoeslag aanvragen",
        description: "Rotterdammers met een inkomen tot 130% van het sociaal minimum komen in aanmerking voor de energietoeslag. Check op rotterdam.nl of je hiervoor in aanmerking komt.",
        icon: "Zap",
        url: "https://www.rotterdam.nl/bijzondere-bijstand-energiekosten-aanvragen",
      },
      {
        title: "Voedselbank Rotterdam",
        description: "Heb je moeite om rond te komen? De Voedselbank Rotterdam heeft meerdere uitgiftepunten in de stad. Aanmelden kan via het wijkteam of maatschappelijk werk.",
        icon: "ShoppingCart",
        url: "https://voedselbank.nl/",
      },
    ],
    ctaText: "Begin vandaag met overzicht in je rekeningen",
    gemeenteUrl: "https://www.rotterdam.nl/",
    coordinates: { lat: 51.9244, lng: 4.4777 },
    logoDomain: "rotterdam.nl",
    debtPercentage: 20,
  },

  amsterdam: {
    slug: "amsterdam",
    name: "Amsterdam",
    province: "Noord-Holland",
    population: "920.000+",
    accentColor: "#C8102E",
    accentColorLight: "#FDE8EC",
    accentColorName: "Amsterdams rood",
    unsplashQuery: "Amsterdam Netherlands canal houses cityscape",
    unsplashQueryOrgs: "Amsterdam city neighborhood Netherlands",
    metaTitle: "Schuldhulp Amsterdam — Hulp bij schulden in Amsterdam",
    metaDescription: "Schulden in Amsterdam? Bekijk gratis hulporganisaties, schuldhulpverlening via de gemeente en praktische tips. PayWatch helpt je met overzicht in je rekeningen.",
    heroTitle: "Schuldhulp in Amsterdam",
    heroSubtitle: "Alle hulp bij schulden in de hoofdstad op een rij",
    introTitle: "Schulden in Amsterdam: in een dure stad is het snel misgegaan",
    introText: "Amsterdam is een van de duurste steden van Nederland. De huren zijn hoog, de dagelijkse kosten lopen op en het leven in de hoofdstad is niet goedkoop. Het is dan ook niet vreemd dat veel Amsterdammers op een gegeven moment moeite krijgen met het betalen van hun rekeningen. De gemeente Amsterdam heeft een uitgebreid netwerk aan hulporganisaties opgezet om inwoners bij te staan.",
    debtContext: "Door de extreme woningmarkt betalen veel Amsterdammers meer dan 40% van hun inkomen aan huur. In wijken als Nieuw-West, Zuidoost en Noord is het percentage huishoudens met betalingsachterstanden aanzienlijk hoger dan het landelijk gemiddelde. Daarnaast zorgt de groei van de flexeconomie en het toerisme voor een groep werkenden die ondanks een baan financieel kwetsbaar blijft.",
    localSituation: "Amsterdam werkt met het programma 'Pak je Kans' en heeft buurtteams in elke wijk. De stad experimenteert met het automatisch kwijtschelden van schulden bij de gemeente zelf en heeft een speciaal programma voor jongeren met schulden (18-27 jaar). Uniek is ook de samenwerking met woningcorporaties om huisuitzettingen te voorkomen.",
    statsHighlight: "Meer dan 80.000 Amsterdamse huishoudens hebben geregistreerde betalingsachterstanden",
    organizations: [
      {
        name: "Kredietbank Amsterdam",
        url: "https://www.amsterdam.nl/werk-en-inkomen/regelingen-bij-laag-inkomen-pak-je-kans/kredietbank-amsterdam/",
        type: "Gemeentelijke kredietbank",
        description: "De Kredietbank Amsterdam helpt met budgetbeheer, schuldregelingen en sociale kredieten. Ze werken samen met de buurtteams en je kunt je ook rechtstreeks aanmelden via amsterdam.nl/schuldhulp.",
        phone: "14 020",
      },
      {
        name: "Buurtteam Amsterdam",
        url: "https://www.buurtteamamsterdam.nl/hulp-bij-schulden-amsterdam/",
        type: "Buurtteam / lokale hulp",
        description: "In elke Amsterdamse buurt zit een buurtteam dat je gratis helpt met geldzorgen. Ze denken met je mee, helpen met je administratie en verwijzen je door als dat nodig is. Geen wachtlijst voor een eerste gesprek.",
      },
      {
        name: "Grip op Geld (Gemeente Amsterdam)",
        url: "https://www.buurtteamamsterdam.nl/activiteiten/grip-op-je-geld/2030-01-23/",
        type: "Gemeentelijk preventieprogramma",
        description: "Online tools en workshops van de gemeente Amsterdam om grip te krijgen op je geldzaken. Inclusief huishoudboekje, budgetcoach en financiele check-ups. Volledig gratis.",
      },
      {
        name: "SchuldHulpMaatje Amsterdam",
        url: "https://schuldhulpmaatje.nl/amsterdam/",
        type: "Vrijwillige schuldhulp",
        description: "Getrainde vrijwilligers die je persoonlijk begeleiden bij het aanpakken van je schulden. Ze helpen met post openen, brieven beantwoorden en je administratie op orde brengen.",
      },
    ],
    faq: [
      {
        question: "Hoe meld ik me aan voor schuldhulpverlening in Amsterdam?",
        answer: "Je kunt je aanmelden door te bellen naar 14 020, online via amsterdam.nl/schuldhulpverlening, of door langs te gaan bij je buurtteam. Je kunt ook naar een Stadsloket. Binnen twee weken heb je een eerste gesprek.",
      },
      {
        question: "Wat is het verschil tussen een buurtteam en de Kredietbank?",
        answer: "Het buurtteam is je eerste aanspreekpunt en helpt je met allerlei vragen, ook over geld. De Kredietbank is gespecialiseerd in schuldhulpverlening en neemt het over als je een formeel schuldhulptraject nodig hebt. Het buurtteam verwijst je door naar de Kredietbank als dat nodig is.",
      },
      {
        question: "Kan ik als jongere in Amsterdam hulp krijgen bij schulden?",
        answer: "Ja, Amsterdam heeft een speciaal programma voor jongeren van 18 tot 27 jaar met schulden. Je krijgt een persoonlijke coach die je helpt om je schulden aan te pakken en financieel zelfstandig te worden. Meld je aan via het buurtteam of bel 14 020.",
      },
      {
        question: "Wat als ik dreig uit huis gezet te worden?",
        answer: "Neem onmiddellijk contact op met je buurtteam of bel 14 020. Amsterdam heeft convenanten met woningcorporaties om huisuitzettingen door schulden te voorkomen. Er is bijna altijd een oplossing mogelijk, maar snelheid is belangrijk.",
      },
      {
        question: "Ik schaam me voor mijn schulden, is het vertrouwelijk?",
        answer: "Alles wat je bespreekt met het buurtteam, de Kredietbank of vrijwilligersorganisaties is vertrouwelijk. Niemand buiten het hulpverleningsteam krijgt je gegevens te zien. Schulden overkomen veel mensen en er is geen reden voor schaamte.",
      },
      {
        question: "Kan de gemeente mijn gemeentelijke belastingschuld kwijtschelden?",
        answer: "Amsterdam experimenteert met het automatisch kwijtschelden van gemeentelijke schulden voor inwoners in de schuldhulpverlening. Daarnaast kun je kwijtschelding aanvragen voor gemeentelijke belastingen als je een laag inkomen hebt.",
      },
    ],
    tips: [
      {
        title: "Stadspas Amsterdam",
        description: "De Stadspas geeft korting op sport, cultuur en vervoer. Bij een laag inkomen is de pas gratis en krijg je extra tegoed voor activiteiten.",
        icon: "Ticket",
        url: "https://www.amsterdam.nl/stadspas/",
      },
      {
        title: "Collectieve zorgverzekering",
        description: "Als Amsterdammer met een laag inkomen kun je meedoen aan de collectieve zorgverzekering van de gemeente. Dit is vaak goedkoper dan een individuele polis en biedt goede dekking.",
        icon: "Heart",
        url: "https://www.amsterdam.nl/werk-en-inkomen/regelingen-bij-laag-inkomen-pak-je-kans/regelingen-alfabet/collectieve-zorgverzekering/",
      },
      {
        title: "Schulden bij de gemeente? Vraag om pauze",
        description: "Als je gemeentelijke belastingschulden hebt en in een hulptraject zit, kan de invordering worden gepauzeerd. Dit geeft je ademruimte om je andere schulden aan te pakken.",
        icon: "PauseCircle",
      },
      {
        title: "Gratis juridisch advies",
        description: "Via het Juridisch Loket Amsterdam kun je gratis advies krijgen over je rechten als schuldenaar. Handig als je te maken hebt met incassobureaus of deurwaarders.",
        icon: "Scale",
        url: "https://www.juridischloket.nl/contact/amsterdam/",
      },
    ],
    ctaText: "Krijg overzicht in je Amsterdamse rekeningen",
    gemeenteUrl: "https://www.amsterdam.nl/werk-en-inkomen/regelingen-bij-laag-inkomen-pak-je-kans/schuldhulpverlening/",
    coordinates: { lat: 52.3676, lng: 4.9041 },
    logoDomain: "amsterdam.nl",
    debtPercentage: 13,
  },

  "den-haag": {
    slug: "den-haag",
    name: "Den Haag",
    province: "Zuid-Holland",
    population: "555.000+",
    accentColor: "#006338",
    accentColorLight: "#E6F2EC",
    accentColorName: "Haags groen",
    unsplashQuery: "The Hague Netherlands Binnenhof cityscape",
    unsplashQueryOrgs: "The Hague city street Netherlands",
    metaTitle: "Schuldhulp Den Haag — Hulp bij schulden in Den Haag",
    metaDescription: "Schulden in Den Haag? Ontdek gratis schuldhulpverlening, lokale organisaties en praktische tips. PayWatch geeft je overzicht in je rekeningen en waarschuwt op tijd.",
    heroTitle: "Schuldhulp in Den Haag",
    heroSubtitle: "Overzicht van alle hulp bij schulden in de hofstad",
    introTitle: "Schulden in Den Haag: hulp is dichterbij dan je denkt",
    introText: "Den Haag is niet alleen de stad van het Binnenhof en de internationale organisaties. Het is ook een stad met grote tegenstellingen. Van Statenkwartier tot Transvaal, van Scheveningen tot Laak: in elke wijk wonen mensen die worstelen met schulden. De gemeente Den Haag heeft schuldhulpverlening hoog op de agenda staan en biedt uitgebreide ondersteuning.",
    debtContext: "Den Haag kent wijken waar meer dan 25% van de huishoudens te maken heeft met geregistreerde betalingsachterstanden. Vooral in Laak, Transvaal en Moerwijk is de schuldproblematiek groot. De diverse samenstelling van de stad, met veel internationale inwoners en statushouders, vraagt om schuldhulp in meerdere talen en met culturele gevoeligheid.",
    localSituation: "De gemeente Den Haag werkt met een centraal aanmeldpunt voor schuldhulpverlening en heeft een netwerk van sociale wijkteams. Bijzonder is het programma 'Financieel Fit' dat zich richt op preventie: mensen leren omgaan met geld voordat er schulden ontstaan. Ook heeft Den Haag een speciaal noodfonds voor acute situaties, zoals dreigende afsluiting van gas en licht.",
    statsHighlight: "In bepaalde Haagse wijken heeft meer dan 1 op de 4 huishoudens betalingsachterstanden",
    organizations: [
      {
        name: "Kredietbank Den Haag",
        url: "https://www.denhaag.nl/nl/geld-en-schulden/geld-lenen-bij-de-gemeentelijke-kredietbank/",
        type: "Gemeentelijke kredietbank",
        description: "De Kredietbank Den Haag biedt schuldhulpverlening, budgetbeheer en sociale kredieten. Aanmelden kan telefonisch via 14 070 of online. Je wordt dan uitgenodigd voor een intakegesprek.",
        phone: "14 070",
      },
      {
        name: "Sociale Wijkteams Den Haag",
        url: "https://socialekaartdenhaag.nl/ak-organisation/wijkteam-haaglanden/",
        type: "Wijkteam / eerste aanspreekpunt",
        description: "In elk stadsdeel van Den Haag is een sociaal wijkteam actief. Ze helpen met geldzorgen, maar ook met andere problemen die daarmee samenhangen, zoals wonen, werk en gezondheid.",
        phone: "14 070",
      },
      {
        name: "SchuldHulpMaatje Den Haag",
        url: "https://schuldhulpmaatje.nl/den-haag/",
        type: "Vrijwillige schuldhulp",
        description: "Persoonlijke begeleiding door getrainde vrijwilligers. Ze helpen je met het ordenen van je administratie, het beantwoorden van post en het begeleiden naar professionele hulp.",
      },
      {
        name: "Vluchtelingenwerk Den Haag (financiele hulp)",
        url: "https://www.vluchtelingenwerk.nl/nl",
        type: "Gespecialiseerde hulp",
        description: "Specifieke ondersteuning voor statushouders en vluchtelingen met schulden. Hulp in meerdere talen en met begrip voor de specifieke situatie van nieuwkomers in Nederland.",
      },
    ],
    faq: [
      {
        question: "Hoe kan ik schuldhulpverlening aanvragen in Den Haag?",
        answer: "Bel 14 070 of ga naar denhaag.nl/geld-en-schulden. Je kunt ook langsgaan bij een sociaal wijkteam in je buurt. Na aanmelding volgt een intakegesprek waarin je situatie wordt beoordeeld en een plan wordt gemaakt.",
      },
      {
        question: "Is er schuldhulp beschikbaar in andere talen?",
        answer: "Ja, Den Haag biedt schuldhulpverlening met tolken en er zijn organisaties die specifiek helpen in het Engels, Arabisch, Turks en andere talen. Vraag bij het wijkteam naar de mogelijkheden.",
      },
      {
        question: "Wat is het noodfonds van Den Haag?",
        answer: "Het gemeentelijk noodfonds kan ingezet worden bij acute situaties, zoals dreigende afsluiting van energie of water, of een dreigende huisuitzetting. Het wijkteam kan je helpen met een aanvraag. Dit is een gift, geen lening.",
      },
      {
        question: "Kan ik hulp krijgen als zzp'er in Den Haag?",
        answer: "Zeker. Steeds meer zzp'ers krijgen te maken met schulden. De gemeente Den Haag biedt ook voor ondernemers en zzp'ers schuldhulpverlening aan. Er is extra aandacht voor de specifieke situatie van zelfstandigen.",
      },
      {
        question: "Hoe werkt vroegsignalering in Den Haag?",
        answer: "Net als in andere grote steden ontvangt de gemeente signalen van energieleveranciers, zorgverzekeraars en woningcorporaties. Als je meerdere betalingsachterstanden hebt, neemt het wijkteam proactief contact met je op om hulp aan te bieden.",
      },
      {
        question: "Wat is het verschil tussen een minnelijke regeling en WSNP?",
        answer: "Bij een minnelijke regeling probeert de Kredietbank met al je schuldeisers een akkoord te bereiken. Je betaalt 18 tot 36 maanden wat je kunt missen, daarna worden de restschulden kwijtgescholden. WSNP is de wettelijke variant via de rechtbank en duurt 18 maanden, maar is strenger.",
      },
    ],
    tips: [
      {
        title: "Ooievaarspas",
        description: "De Ooievaarspas geeft Hagenaars met een laag inkomen korting op sport, cultuur en openbaar vervoer. Aanvragen kan via denhaag.nl.",
        icon: "Ticket",
        url: "https://www.denhaag.nl/nl/geld-en-schulden/ooievaarspas-aanvragen/",
      },
      {
        title: "Gratis budgetcoaching",
        description: "Via het programma 'Financieel Fit' kun je gratis budgetcoaching volgen. Je leert omgaan met je geld en voorkomt dat kleine problemen uitgroeien tot grote schulden.",
        icon: "GraduationCap",
        url: "https://www.denhaag.nl/nl/geld-en-schulden/hulp-bij-geldzaken/",
      },
      {
        title: "Kindpakket Den Haag",
        description: "Gezinnen met een laag inkomen kunnen aanspraak maken op het Kindpakket: een vergoeding voor schoolspullen, sportcontributies en andere kosten voor kinderen.",
        icon: "Baby",
        url: "https://www.denhaag.nl/nl/onderwijs-en-studeren/fondsen-voor-schoolkosten/",
      },
      {
        title: "Gratis belastingaangifte",
        description: "Via diverse Haagse organisaties kun je gratis hulp krijgen bij je belastingaangifte. Dit voorkomt boetes en zorgt ervoor dat je alle toeslagen krijgt waar je recht op hebt.",
        icon: "FileText",
        url: "https://socialekaartdenhaag.nl/ak-subject/belastingaangifte/",
      },
    ],
    ctaText: "Krijg grip op je rekeningen in Den Haag",
    gemeenteUrl: "https://www.denhaag.nl/nl/geld-en-schulden/",
    coordinates: { lat: 52.0705, lng: 4.3007 },
    logoDomain: "denhaag.nl",
    debtPercentage: 14,
  },

  utrecht: {
    slug: "utrecht",
    name: "Utrecht",
    province: "Utrecht",
    population: "365.000+",
    accentColor: "#C8102E",
    accentColorLight: "#FDE8EC",
    accentColorName: "Utrechts rood",
    unsplashQuery: "Utrecht Netherlands Dom tower canal",
    unsplashQueryOrgs: "Utrecht city Netherlands street",
    metaTitle: "Schuldhulp Utrecht — Gratis hulp bij schulden in Utrecht",
    metaDescription: "Schulden in Utrecht? Vind gratis schuldhulpverlening, lokale hulporganisaties en tips om je financien op orde te krijgen. PayWatch helpt je met grip op je rekeningen.",
    heroTitle: "Schuldhulp in Utrecht",
    heroSubtitle: "Alle hulp bij schulden in de Domstad",
    introTitle: "Schulden in Utrecht: ook in een welvarende stad loopt het mis",
    introText: "Utrecht staat bekend als een van de meest welvarende steden van Nederland. Maar achter die statistiek schuilt een ander verhaal. Ook in Utrecht zijn er duizenden huishoudens die moeite hebben om rond te komen. Studenten die na hun studie met schulden achterblijven, jonge gezinnen die de huur nauwelijks kunnen betalen en ouderen met een klein pensioen. De gemeente Utrecht pakt schulden proactief aan.",
    debtContext: "De woningmarkt in Utrecht is extreem krap. Huurprijzen zijn de afgelopen jaren fors gestegen, ook in wijken die voorheen betaalbaar waren, zoals Overvecht, Kanaleneiland en Zuilen. Voor veel Utrechters gaat meer dan de helft van hun inkomen naar woonlasten. Dat laat weinig ruimte voor onverwachte kosten. Een kapotte wasmachine of een naheffing van de Belastingdienst kan dan al het begin zijn van een schuldenspiraal.",
    localSituation: "Utrecht werkt met buurtteams die laagdrempelig bereikbaar zijn. De stad is een van de koplopers in het toepassen van de Wet gemeentelijke schuldhulpverlening en experimenteert met het eerder kwijtschelden van schulden. Utrecht heeft ook een speciaal project voor mensen die net niet in aanmerking komen voor formele schuldhulp maar wel geldzorgen hebben.",
    statsHighlight: "In Overvecht en Kanaleneiland heeft meer dan 15% van de huishoudens problematische schulden",
    organizations: [
      {
        name: "Werk en Inkomen Utrecht",
        url: "https://www.utrecht.nl/zorg-en-onderwijs/hulp-bij-schulden/",
        type: "Gemeentelijke dienst",
        description: "De afdeling Werk en Inkomen van de gemeente Utrecht is het startpunt voor schuldhulpverlening. Zij regelen de intake, beoordelen je situatie en starten het hulptraject op. Aanmelden via het buurtteam of telefonisch.",
        phone: "14 030",
      },
      {
        name: "Buurtteams Utrecht",
        url: "https://www.buurtteamsutrecht.nl",
        type: "Buurtteam / eerste aanspreekpunt",
        description: "De Utrechtse buurtteams zijn je eerste aanspreekpunt voor hulp bij geldzorgen. Ze helpen je met praktische zaken, verwijzen door naar schuldhulpverlening en ondersteunen je tijdens het hele traject.",
      },
      {
        name: "Stadsgeldbeheer",
        url: "https://www.stadsgeldbeheer.nl",
        type: "Budgetbeheer",
        description: "Stadsgeldbeheer helpt Utrechters die moeite hebben met het beheren van hun geld. Ze nemen tijdelijk je financien over, betalen vaste lasten en zorgen dat er geen nieuwe schulden ontstaan.",
      },
      {
        name: "U-Centraal (Maatschappelijk Werk)",
        url: "https://www.u-centraal.nl",
        type: "Psychosociale ondersteuning",
        description: "Schulden gaan vaak gepaard met stress, schaamte en andere problemen. U-Centraal biedt gratis maatschappelijk werk en psychosociale ondersteuning naast de financiele hulp.",
      },
    ],
    faq: [
      {
        question: "Hoe vraag ik schuldhulpverlening aan in Utrecht?",
        answer: "Neem contact op met je buurtteam of bel 14 030. Je kunt ook online een aanvraag indienen via utrecht.nl. Na je aanmelding volgt een eerste gesprek waarin je situatie in kaart wordt gebracht.",
      },
      {
        question: "Ik ben student in Utrecht en heb schulden, kan ik hulp krijgen?",
        answer: "Ja, ook studenten kunnen gebruikmaken van schuldhulpverlening in Utrecht. Neem contact op met het buurtteam in je wijk. Daarnaast heeft de Universiteit Utrecht en de Hogeschool Utrecht studentenpsychologen die ook bij financiele stress kunnen helpen.",
      },
      {
        question: "Wat is budgetbeheer en is dat iets voor mij?",
        answer: "Bij budgetbeheer neemt een organisatie tijdelijk het beheer van je financien over. Je inkomen komt op een beheerrekening, vaste lasten worden automatisch betaald en jij krijgt leefgeld. Dit voorkomt dat je nieuwe schulden maakt terwijl je oude schulden worden afgelost.",
      },
      {
        question: "Kan ik ook hulp krijgen als mijn schulden klein zijn?",
        answer: "Ja, Utrecht heeft ook hulp voor mensen met beginnende geldzorgen. Je hoeft niet te wachten tot de situatie onhoudbaar wordt. Hoe eerder je hulp zoekt, hoe makkelijker en sneller het op te lossen is.",
      },
      {
        question: "Hoeveel schulden moet ik hebben voor schuldhulpverlening?",
        answer: "Er is geen minimumbedrag. Als je je schulden niet meer kunt overzien of betalen, heb je recht op hulp. De gemeente kijkt naar je totale situatie: inkomen, vaste lasten, schulden en persoonlijke omstandigheden.",
      },
      {
        question: "Wat als ik zelfstandig ondernemer ben?",
        answer: "Utrecht biedt ook schuldhulpverlening aan zzp'ers en zelfstandig ondernemers. Er is extra expertise beschikbaar voor de specifieke situatie van ondernemers, zoals BTW-schulden en zakelijke schulden.",
      },
    ],
    tips: [
      {
        title: "U-pas",
        description: "Met de U-pas krijg je korting op sport, cultuur en openbaar vervoer in Utrecht. Bij een laag inkomen is de pas gratis. Aanvragen via utrecht.nl.",
        icon: "Ticket",
      },
      {
        title: "Individuele inkomenstoeslag",
        description: "Als je al langer dan 3 jaar een laag inkomen hebt, kun je bij de gemeente Utrecht een individuele inkomenstoeslag aanvragen. Dit is een eenmalig bedrag dat je vrij kunt besteden.",
        icon: "Coins",
      },
      {
        title: "Gratis juridisch spreekuur",
        description: "Het Juridisch Loket Utrecht biedt gratis juridisch advies. Handig als je vragen hebt over je rechten bij incasso, loonbeslag of andere juridische aspecten van je schulden.",
        icon: "Scale",
      },
      {
        title: "Voedselbank Utrecht",
        description: "Als je onvoldoende geld hebt voor boodschappen, kun je via het buurtteam aangemeld worden bij de Voedselbank Utrecht. Ze hebben meerdere uitgiftepunten in de stad.",
        icon: "ShoppingCart",
      },
    ],
    ctaText: "Krijg grip op je rekeningen in Utrecht",
    gemeenteUrl: "https://www.utrecht.nl/zorg-en-onderwijs/hulp-bij-schulden/",
    coordinates: { lat: 52.0907, lng: 5.1214 },
    logoDomain: "utrecht.nl",
    debtPercentage: 11,
  },

  eindhoven: {
    slug: "eindhoven",
    name: "Eindhoven",
    province: "Noord-Brabant",
    population: "240.000+",
    accentColor: "#1E3A8A",
    accentColorLight: "#E8EDF8",
    accentColorName: "Eindhovens blauw",
    unsplashQuery: "Eindhoven Netherlands technology city skyline",
    unsplashQueryOrgs: "Eindhoven Brabant Netherlands street",
    metaTitle: "Schuldhulp Eindhoven — Hulp bij schulden in Eindhoven",
    metaDescription: "Schulden in Eindhoven? Ontdek gratis hulporganisaties, schuldhulpverlening en tips om financieel gezond te worden. PayWatch geeft je overzicht en waarschuwt op tijd.",
    heroTitle: "Schuldhulp in Eindhoven",
    heroSubtitle: "Alle hulp bij schulden in de Lichtstad",
    introTitle: "Schulden in Eindhoven: ook in de techstad liggen financiele problemen op de loer",
    introText: "Eindhoven groeit snel. De techsector bloeit, er worden nieuwe wijken gebouwd en de stad trekt mensen van over de hele wereld aan. Maar niet iedereen deelt mee in die groei. In Eindhoven wonen ook veel mensen met een laag inkomen die moeite hebben om rond te komen. De gemeente Eindhoven zet zich actief in voor schuldhulpverlening en heeft een stevig netwerk van hulporganisaties opgebouwd.",
    debtContext: "Achter het succes van de Brainportregio schuilt een andere werkelijkheid. In wijken als Woensel-Zuid, Gestel en Tongelre worstelen veel huishoudens met schulden. De snelle groei van de stad heeft de huurprijzen omhooggeduwd. Tegelijkertijd zijn er in Eindhoven veel arbeidsmigranten en expats die niet altijd goed op de hoogte zijn van hun rechten en beschikbare hulp. De gemeente zet daarom extra in op bereikbaarheid en meertalige voorlichting.",
    localSituation: "Eindhoven werkt met WIJeindhoven, een organisatie die in elke wijk aanwezig is en fungeert als eerste aanspreekpunt voor alle sociale vragen, inclusief geldzorgen. De stad werkt nauw samen met woningcorporaties Woonbedrijf en 'thuis om betalingsachterstanden bij huurders vroegtijdig te signaleren. Ook is er een speciaal loket voor ondernemers met schulden, in samenwerking met de Kamer van Koophandel.",
    statsHighlight: "In Woensel-Zuid heeft bijna 1 op de 5 huishoudens te maken met problematische schulden",
    organizations: [
      {
        name: "Schuldhulpverlening Eindhoven (gemeente)",
        url: "https://www.eindhoven.nl/",
        type: "Gemeentelijke schuldhulp",
        description: "De gemeente Eindhoven biedt volledige schuldhulpverlening: van intake en budgetcoaching tot schuldregelingen en doorverwijzing naar WSNP. Aanmelden via WIJeindhoven of telefonisch.",
        phone: "14 040",
      },
      {
        name: "WIJeindhoven",
        url: "https://www.wijeindhoven.nl",
        type: "Sociaal wijkteam",
        description: "WIJeindhoven is er voor alle Eindhovenaren met vragen over geld, werk, opvoeding en meer. In elk stadsdeel is een team aanwezig. Je kunt zonder afspraak binnenlopen voor een eerste gesprek over je geldzorgen.",
        phone: "040 212 4040",
      },
      {
        name: "Lumens",
        url: "https://www.lumens.nu",
        type: "Welzijnsorganisatie",
        description: "Lumens biedt informele schuldhulp, thuisadministratie en maatjesprojecten. Getrainde vrijwilligers helpen je met het ordenen van je financien en begeleiden je naar professionele hulp als dat nodig is.",
      },
      {
        name: "PlusTeam Eindhoven",
        url: "https://www.plusteameindhoven.nl",
        type: "Gespecialiseerde hulp",
        description: "Voor complexere situaties waar schulden samengaan met andere problemen, zoals verslaving, psychische klachten of huiselijk geweld. Het PlusTeam biedt integrale ondersteuning.",
      },
    ],
    faq: [
      {
        question: "Hoe vraag ik schuldhulpverlening aan in Eindhoven?",
        answer: "Loop binnen bij WIJeindhoven in je wijk, bel 14 040 of meld je aan via eindhoven.nl/schulden. Je krijgt een eerste gesprek waarin je situatie wordt bekeken. Daarna wordt besloten welke hulp het best bij je past.",
      },
      {
        question: "Is er hulp voor arbeidsmigranten met schulden in Eindhoven?",
        answer: "Ja, Eindhoven heeft speciale aandacht voor arbeidsmigranten en expats. Er is hulp beschikbaar in het Engels en via tolken ook in andere talen. WIJeindhoven heeft ervaring met de specifieke problemen waar internationale inwoners tegenaan lopen.",
      },
      {
        question: "Wat doet WIJeindhoven precies bij geldzorgen?",
        answer: "WIJeindhoven is je eerste aanspreekpunt. Ze luisteren naar je verhaal, brengen je situatie in kaart en bepalen welke hulp je nodig hebt. Dit kan varieren van een eenmalig adviesgesprek tot een verwijzing naar formele schuldhulpverlening.",
      },
      {
        question: "Kan ik hulp krijgen als ondernemer in Eindhoven?",
        answer: "Zeker. Eindhoven heeft een speciaal loket voor ondernemers met schulden, in samenwerking met de Kamer van Koophandel. Er is expertise beschikbaar voor zakelijke schulden, BTW-problematiek en de combinatie van prive- en zakelijke schulden.",
      },
      {
        question: "Hoe lang duurt het voordat ik geholpen word?",
        answer: "Voor een eerste gesprek bij WIJeindhoven kun je vaak zonder afspraak terecht. Voor een formeel schuldhulptraject geldt een wettelijke termijn van maximaal 4 weken na aanmelding voor het eerste gesprek. In de praktijk lukt dit in Eindhoven meestal sneller.",
      },
      {
        question: "Moet ik al mijn schulden kennen voordat ik hulp kan vragen?",
        answer: "Nee, je hoeft niet een compleet overzicht te hebben. De schuldhulpverlener helpt je juist met het in kaart brengen van al je schulden. Neem mee wat je hebt aan brieven en post, en de rest wordt uitgezocht.",
      },
    ],
    tips: [
      {
        title: "Eindhoven Sportief en Cultureel",
        description: "Met een laag inkomen kun je in Eindhoven deelnemen aan diverse sport- en cultuurregelingen. Dit zijn geen leningen, maar vergoedingen. Vraag ernaar bij WIJeindhoven.",
        icon: "Trophy",
      },
      {
        title: "Energiecoach Eindhoven",
        description: "Gratis energiecoaches helpen je om je energieverbruik te verlagen. Ze komen bij je thuis langs en geven concrete tips. Dit kan je tientallen euros per maand besparen.",
        icon: "Zap",
      },
      {
        title: "Kwijtschelding gemeentelijke belastingen",
        description: "Eindhovenaren met een laag inkomen kunnen kwijtschelding aanvragen voor gemeentelijke belastingen en afvalstoffenheffing. Doe dit elk jaar opnieuw via eindhoven.nl.",
        icon: "BadgePercent",
        url: "https://www.rotterdam.nl/kwijtschelding-afvalstoffenheffing-aanvragen",
      },
      {
        title: "Samen rond de tafel met schuldeisers",
        description: "In Eindhoven wordt steeds vaker gewerkt met een 'breed moratorium': een pauze van afbetalingen aan alle schuldeisers tegelijk, zodat je rust krijgt om een plan te maken.",
        icon: "Users",
      },
    ],
    ctaText: "Begin vandaag met overzicht in je rekeningen",
    gemeenteUrl: "https://www.eindhoven.nl/",
    coordinates: { lat: 51.4416, lng: 5.4697 },
    logoDomain: "eindhoven.nl",
    debtPercentage: 12,
  },

  groningen: {
    slug: "groningen",
    name: "Groningen",
    province: "Groningen",
    population: "235.000+",
    accentColor: "#00843D",
    accentColorLight: "#E6F5ED",
    accentColorName: "Gronings groen",
    unsplashQuery: "Groningen Netherlands Martinitoren canal",
    unsplashQueryOrgs: "Groningen city Netherlands",
    metaTitle: "Schuldhulp Groningen — Gratis hulp bij schulden",
    metaDescription: "Schulden in Groningen? Ontdek gratis hulporganisaties, schuldhulpverlening via de gemeente en praktische tips. PayWatch helpt je met overzicht.",
    heroTitle: "Schuldhulp in Groningen",
    heroSubtitle: "Alle hulp bij schulden in de Martinistad",
    introTitle: "Schulden in Groningen: een studentenstad met verborgen armoede",
    introText: "Groningen is bekend als bruisende studentenstad, maar kent ook buurten waar armoede en schulden deel uitmaken van het dagelijks leven. In wijken als Paddepoel, Vinkhuizen en de Oosterparkwijk hebben relatief veel huishoudens te maken met betalingsachterstanden. De gemeente Groningen pakt schulden actief aan met preventie en vroegsignalering.",
    debtContext: "Als centrumgemeente van Noord-Nederland trekt Groningen veel inwoners aan met lagere inkomens. De woningmarkt is door de groei van de universiteit onder druk komen te staan. Veel jongeren en starters hebben moeite om een betaalbare woning te vinden. Daarnaast zorgen de gevolgen van de gaswinning in sommige buurten voor extra financiele stress.",
    localSituation: "Groningen werkt met WIJ-teams die in elk stadsdeel aanwezig zijn. De stad is actief bezig met het vereenvoudigen van schuldhulpverlening en experimenteert met het automatisch kwijtschelden van kleine gemeentelijke schulden. Er is ook een speciaal project voor studenten met schulden.",
    statsHighlight: "In Paddepoel en Vinkhuizen heeft meer dan 18% van de huishoudens problematische schulden",
    organizations: [
      { name: "WIJ Groningen", url: "https://wij.groningen.nl", type: "Sociaal wijkteam", description: "In elk stadsdeel van Groningen is WIJ aanwezig. Ze helpen gratis met geldzorgen, administratie en verwijzen door naar schuldhulpverlening.", phone: "050 367 4200" },
      { name: "Schuldhulpverlening gemeente Groningen", url: "https://gemeente.groningen.nl/", type: "Gemeentelijke schuldhulp", description: "De gemeente biedt volledige schuldhulpverlening: van intake tot schuldregeling. Aanmelden via WIJ of telefonisch via 14 050.", phone: "14 050" },
      { name: "Humanitas Groningen", url: "https://www.humanitasgroningen.nl", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en budgetmaatjes. Vrijwilligers die je helpen met je post, administratie en betalingen." },
    ],
    faq: [
      { question: "Hoe vraag ik schuldhulpverlening aan in Groningen?", answer: "Neem contact op met WIJ in je wijk of bel 14 050. Je kunt ook online een aanvraag doen via gemeente.groningen.nl/schulden." },
      { question: "Is er hulp voor studenten met schulden?", answer: "Ja, Groningen heeft speciale programma's voor studenten. Neem contact op met WIJ of het studentendecanaat van de RUG of Hanzehogeschool." },
      { question: "Hoe lang duurt schuldhulpverlening in Groningen?", answer: "Een minnelijke schuldregeling duurt gemiddeld 18 tot 36 maanden. Het eerste gesprek vindt binnen 4 weken na aanmelding plaats." },
      { question: "Kan ik kwijtschelding krijgen van gemeentelijke belastingen?", answer: "Ja, Groningers met een laag inkomen kunnen kwijtschelding aanvragen. Dit geldt voor gemeentelijke belastingen en waterschapsbelasting." },
      { question: "Wat als ik de aardbevingsschade nog niet vergoed heb gekregen?", answer: "Financiele stress door de gaswinning is een erkend probleem. WIJ kan je doorverwijzen naar het Instituut Mijnbouwschade en tegelijk helpen met je schulden." },
    ],
    tips: [
      { title: "Stadjerspas", description: "Met een laag inkomen krijg je gratis de Stadjerspas voor korting op sport, cultuur en vervoer.", icon: "Ticket" },
      { title: "Kwijtschelding gemeentebelasting", description: "Vraag jaarlijks kwijtschelding aan via gemeente.groningen.nl. Dit kan honderden euros schelen.", icon: "BadgePercent" },
      { title: "Gratis energieadvies", description: "Buurtwarmte Groningen biedt gratis energieadvies aan huis. Zo bespaar je op je energierekening.", icon: "Zap" },
    ],
    ctaText: "Krijg grip op je rekeningen in Groningen",
    gemeenteUrl: "https://gemeente.groningen.nl/",
    coordinates: { lat: 53.2194, lng: 6.5665 },
    logoDomain: "groningen.nl",
    debtPercentage: 15,
  },

  tilburg: {
    slug: "tilburg",
    name: "Tilburg",
    province: "Noord-Brabant",
    population: "225.000+",
    accentColor: "#E30613",
    accentColorLight: "#FDE8EA",
    accentColorName: "Tilburgs rood",
    unsplashQuery: "Tilburg Netherlands city Brabant",
    unsplashQueryOrgs: "Tilburg Netherlands street",
    metaTitle: "Schuldhulp Tilburg — Gratis hulp bij schulden",
    metaDescription: "Schulden in Tilburg? Vind gratis schuldhulpverlening, hulporganisaties en tips. PayWatch helpt je met overzicht in je rekeningen.",
    heroTitle: "Schuldhulp in Tilburg",
    heroSubtitle: "Overzicht van alle hulp bij schulden in Tilburg",
    introTitle: "Schulden in Tilburg: Brabantse nuchterheid helpt je verder",
    introText: "Tilburg is een warme Brabantse stad waar gemeenschapszin groot is. Maar ook hier worstelen duizenden huishoudens met schulden. De textielindustrie is grotendeels verdwenen en niet iedereen heeft de overstap naar de nieuwe economie kunnen maken. De gemeente Tilburg investeert fors in armoedebeleid en schuldhulpverlening.",
    debtContext: "In wijken als Tilburg-Noord, Stokhasselt en Groenewoud is het percentage huishoudens met problematische schulden bovengemiddeld. Tilburg kent een relatief grote groep werkenden met een laag inkomen, de zogenoemde werkende armen. Voor hen is schuldhulpverlening via de gemeente ook beschikbaar.",
    localSituation: "Tilburg werkt met de sociale wijkteams van ContourdeTwern. De stad heeft een uitgebreid pakket aan armoederegelingen en is een van de gemeenten die experimenteert met een ruimhartiger beleid bij het kwijtschelden van schulden.",
    statsHighlight: "Tilburg heeft meer dan 15.000 huishoudens die leven van een inkomen onder de armoedegrens",
    organizations: [
      { name: "Schuldhulpverlening gemeente Tilburg", url: "https://www.tilburg.nl/schulden", type: "Gemeentelijke schuldhulp", description: "De gemeente Tilburg biedt gratis schuldhulpverlening. Aanmelden kan telefonisch of via het Stadskantoor.", phone: "14 013" },
      { name: "ContourdeTwern", url: "https://www.contourdetwern.nl", type: "Sociaal wijkteam", description: "De wijkteams van ContourdeTwern zijn je eerste aanspreekpunt in Tilburg. Ze helpen met geldzorgen en verwijzen door." },
      { name: "SchuldHulpMaatje Tilburg", url: "https://schuldhulpmaatje.nl/tilburg/", type: "Vrijwillige schuldhulp", description: "Vrijwilligers die je persoonlijk begeleiden bij het aanpakken van je schulden en administratie." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Tilburg?", answer: "Bel 14 013 of loop binnen bij het Stadskantoor aan de Spoorlaan. Je kunt ook via een wijkteam worden doorverwezen." },
      { question: "Wat zijn de armoederegelingen in Tilburg?", answer: "Tilburg heeft een ruim pakket: individuele inkomenstoeslag, collectieve zorgverzekering, Stadspas en vergoedingen voor sport en cultuur voor kinderen." },
      { question: "Kan ik als werkende ook hulp krijgen?", answer: "Ja, ook werkenden met schulden hebben recht op schuldhulpverlening. De gemeente kijkt naar je hele financiele situatie." },
      { question: "Hoe snel word ik geholpen?", answer: "Wettelijk moet het eerste gesprek binnen 4 weken plaatsvinden. Bij acute noodsituaties, zoals dreigende huisuitzetting, kan dit sneller." },
    ],
    tips: [
      { title: "Stadspas Tilburg", description: "Gratis bij een laag inkomen. Geeft korting op sport, cultuur en vervoer in Tilburg.", icon: "Ticket" },
      { title: "Collectieve zorgverzekering", description: "Via de gemeente kun je meedoen aan een voordelige collectieve zorgpolis.", icon: "Heart" },
      { title: "Meedoen Tilburg", description: "Vergoedingen voor sport- en cultuuractiviteiten voor kinderen uit gezinnen met een laag inkomen.", icon: "Trophy" },
    ],
    ctaText: "Krijg grip op je rekeningen in Tilburg",
    gemeenteUrl: "https://www.tilburg.nl/",
    coordinates: { lat: 51.5555, lng: 5.0913 },
    logoDomain: "tilburg.nl",
    debtPercentage: 13,
  },

  almere: {
    slug: "almere",
    name: "Almere",
    province: "Flevoland",
    population: "220.000+",
    accentColor: "#0066B3",
    accentColorLight: "#E6F0FA",
    accentColorName: "Almere blauw",
    unsplashQuery: "Almere Netherlands modern architecture",
    unsplashQueryOrgs: "Almere Flevoland Netherlands",
    metaTitle: "Schuldhulp Almere — Gratis hulp bij schulden",
    metaDescription: "Schulden in Almere? Ontdek gratis schuldhulpverlening en lokale hulporganisaties. PayWatch helpt je met grip op je rekeningen.",
    heroTitle: "Schuldhulp in Almere",
    heroSubtitle: "Alle hulp bij schulden in de jongste stad van Nederland",
    introTitle: "Schulden in Almere: jong, groeiend, kwetsbaar",
    introText: "Almere is de jongste grote stad van Nederland en groeit nog steeds. Veel inwoners zijn vanuit Amsterdam en andere steden naar Almere verhuisd op zoek naar betaalbare woningen. Maar ook in Almere stijgen de kosten. De gemeente zet zich actief in voor schuldhulpverlening en preventie.",
    debtContext: "Almere kent een relatief jonge bevolking met veel gezinnen. De combinatie van hoge hypotheeklasten, kinderopvangkosten en stijgende energieprijzen maakt veel Almeerders financieel kwetsbaar. In Almere Poort en Almere Buiten groeien de betalingsachterstanden.",
    localSituation: "De gemeente Almere werkt samen met Verder voor de uitvoering van schuldhulpverlening. Er zijn spreekuren in elke wijk en er is een speciaal programma voor jongeren tot 27 jaar met schulden.",
    statsHighlight: "Almere telt naar schatting 12.000 huishoudens met risicovolle schulden",
    organizations: [
      { name: "Verder (schuldhulpverlening)", url: "https://www.verdergroep.nl/schuldhulpverlening-aanvragen/", type: "Uitvoerende schuldhulporganisatie", description: "Verder voert de schuldhulpverlening uit namens de gemeente Almere. Ze bieden budgetcoaching, schuldregelingen en nazorg.", phone: "036 539 9339" },
      { name: "Gemeente Almere (sociaal domein)", url: "https://www.almere.nl/werk-en-inkomen/schulden", type: "Gemeentelijk loket", description: "Het gemeentelijk loket voor werk en inkomen is je startpunt voor alle geldzorgen. Aanmelden telefonisch of online.", phone: "14 036" },
      { name: "Humanitas Flevoland", url: "https://www.humanitas.nl/flevoland", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en financiele coaching door vrijwilligers. Laagdrempelig en gratis." },
    ],
    faq: [
      { question: "Hoe vraag ik schuldhulpverlening aan in Almere?", answer: "Bel 14 036 of meld je aan via almere.nl. Je wordt doorverwezen naar Verder voor een intakegesprek." },
      { question: "Is er hulp voor jongeren met schulden?", answer: "Ja, Almere heeft een speciaal traject voor jongeren tot 27 jaar. Neem contact op via het jongerenloket." },
      { question: "Wat als ik een hoge hypotheek heb en niet meer kan betalen?", answer: "Ook bij hypotheekschulden kun je hulp krijgen. De schuldhulpverlener kan bemiddelen met je hypotheekverstrekker en een oplossing zoeken." },
      { question: "Hoe lang duurt een schuldhulptraject?", answer: "Gemiddeld 18 tot 36 maanden voor een minnelijke regeling. Het eerste gesprek vindt binnen 4 weken na aanmelding plaats." },
    ],
    tips: [
      { title: "AmerenPas", description: "Korting op sport, cultuur en openbaar vervoer voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding belastingen", description: "Almeerders met een laag inkomen kunnen kwijtschelding aanvragen voor gemeentelijke belastingen.", icon: "BadgePercent" },
      { title: "Energietoeslag", description: "Huishoudens met een laag inkomen komen in aanmerking voor de energietoeslag. Check almere.nl.", icon: "Zap" },
    ],
    ctaText: "Begin met overzicht in je rekeningen",
    gemeenteUrl: "https://www.almere.nl/werk-en-inkomen/schulden",
    coordinates: { lat: 52.3508, lng: 5.2647 },
    logoDomain: "almere.nl",
    debtPercentage: 10,
  },

  breda: {
    slug: "breda",
    name: "Breda",
    province: "Noord-Brabant",
    population: "185.000+",
    accentColor: "#1B3C6E",
    accentColorLight: "#E8ECF2",
    accentColorName: "Bredaas blauw",
    unsplashQuery: "Breda Netherlands Grote Kerk historic city",
    unsplashQueryOrgs: "Breda Brabant Netherlands",
    metaTitle: "Schuldhulp Breda — Gratis hulp bij schulden",
    metaDescription: "Schulden in Breda? Vind gratis schuldhulpverlening, de Kredietbank West-Brabant en praktische tips. PayWatch geeft je overzicht.",
    heroTitle: "Schuldhulp in Breda",
    heroSubtitle: "Overzicht van alle hulp bij schulden in Breda",
    introTitle: "Schulden in Breda: in de parel van het zuiden is hulp dichtbij",
    introText: "Breda combineert historische charme met een moderne uitstraling. Maar ook hier zijn er inwoners die worstelen met schulden. De Kredietbank West-Brabant speelt een centrale rol in de schuldhulpverlening in Breda en omgeving. De gemeente investeert in vroege signalering en preventie.",
    debtContext: "In wijken als Hoge Vucht, Geeren-Zuid en Kesteren zijn betalingsachterstanden bovengemiddeld. De combinatie van lagere inkomens en stijgende woonlasten zet huishoudens onder druk. Breda kent daarnaast een groeiende groep zzp'ers die financieel kwetsbaar is.",
    localSituation: "Breda werkt met IMW (Instituut voor Maatschappelijk Werk) als eerste aanspreekpunt en de Kredietbank West-Brabant voor formele schuldhulpverlening. De stad heeft een breed pakket aan armoederegelingen.",
    statsHighlight: "Breda heeft ruim 10.000 huishoudens met betalingsachterstanden op vaste lasten",
    organizations: [
      { name: "Kredietbank West-Brabant", url: "https://www.breda.nl/kredietbank", type: "Kredietbank", description: "Formele schuldhulpverlening voor Breda en omgeving. Schuldregelingen, budgetbeheer en sociale kredieten.", phone: "14 076" },
      { name: "IMW Breda", url: "https://www.imwbreda.nl", type: "Maatschappelijk werk", description: "Eerste aanspreekpunt voor geldzorgen. IMW helpt met administratie, verwijst door en biedt psychosociale ondersteuning." },
      { name: "SchuldHulpMaatje Breda", url: "https://schuldhulpmaatje.nl/breda/", type: "Vrijwillige schuldhulp", description: "Persoonlijke begeleiding door getrainde vrijwilligers bij het aanpakken van je schulden." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Breda?", answer: "Bel 14 076 of neem contact op met IMW Breda. Je kunt ook online een aanvraag doen via breda.nl." },
      { question: "Wat doet de Kredietbank West-Brabant?", answer: "Ze regelen schuldregelingen met je schuldeisers, bieden budgetbeheer en verstrekken sociale kredieten voor noodzakelijke uitgaven." },
      { question: "Is er hulp voor zzp'ers?", answer: "Ja, ook zelfstandigen kunnen in Breda terecht voor schuldhulpverlening. Er is extra aandacht voor de combinatie van zakelijke en prive schulden." },
      { question: "Hoe snel kan ik geholpen worden?", answer: "Het eerste gesprek vindt wettelijk binnen 4 weken plaats. Bij spoed, zoals dreigend energieafsluiting, kan het sneller." },
    ],
    tips: [
      { title: "Bredapas", description: "Korting op sport, cultuur en vervoer voor Bredanaars met een laag inkomen.", icon: "Ticket" },
      { title: "Kindpakket", description: "Vergoedingen voor schoolspullen, sport en uitjes voor kinderen uit gezinnen met een laag inkomen.", icon: "Baby" },
      { title: "Kwijtschelding", description: "Kwijtschelding gemeentebelastingen en afvalstoffenheffing bij laag inkomen. Vraag het jaarlijks aan.", icon: "BadgePercent" },
    ],
    ctaText: "Krijg grip op je rekeningen in Breda",
    gemeenteUrl: "https://www.breda.nl/hulp-bij-geldzorgen-schulden",
    coordinates: { lat: 51.5719, lng: 4.7683 },
    logoDomain: "breda.nl",
    debtPercentage: 11,
  },

  nijmegen: {
    slug: "nijmegen",
    name: "Nijmegen",
    province: "Gelderland",
    population: "180.000+",
    accentColor: "#B51219",
    accentColorLight: "#F9E8E9",
    accentColorName: "Nijmeegs rood",
    unsplashQuery: "Nijmegen Netherlands Waal river city",
    unsplashQueryOrgs: "Nijmegen Gelderland Netherlands",
    metaTitle: "Schuldhulp Nijmegen — Gratis hulp bij schulden",
    metaDescription: "Schulden in Nijmegen? Ontdek gratis hulporganisaties, wijkteams en praktische tips. PayWatch helpt je met overzicht.",
    heroTitle: "Schuldhulp in Nijmegen",
    heroSubtitle: "Alle hulp bij schulden in de oudste stad van Nederland",
    introTitle: "Schulden in Nijmegen: een sociale stad die niemand laat vallen",
    introText: "Nijmegen staat bekend als een sociale stad met een sterk verenigingsleven. De oudste stad van Nederland heeft een lange traditie van solidariteit. Toch kampen ook hier duizenden huishoudens met schulden. De gemeente zet sterk in op preventie en laagdrempelige hulp via de wijkteams.",
    debtContext: "In wijken als Hatert, Neerbosch-Oost en Lindenholt zijn de schuldenproblematiek en armoede het grootst. Nijmegen is een studentenstad, maar ook een stad waar veel gezinnen leven van een minimuminkomen. De wisselwerking tussen lage inkomens en hoge energiekosten treft veel huishoudens.",
    localSituation: "Nijmegen werkt met Stips (Sociale Teams in de Praktijk) als eerste aanspreekpunt. De GKB Nijmegen voert de formele schuldhulpverlening uit. De stad staat bekend om haar ruimhartige armoedebeleid.",
    statsHighlight: "In Hatert en Neerbosch-Oost heeft meer dan 20% van de huishoudens een betalingsachterstand",
    organizations: [
      { name: "GKB Nijmegen", url: "https://www.nijmegen.nl/", type: "Gemeentelijke kredietbank", description: "De GKB voert schuldhulpverlening uit in Nijmegen: schuldregelingen, budgetbeheer en sociale kredieten.", phone: "14 024" },
      { name: "STIP (sociaal wijkteam)", url: "https://www.nijmegen.nl/", type: "Sociaal wijkteam", description: "Stips zijn er in elke wijk. Ze helpen met geldzorgen en verwijzen door naar schuldhulpverlening." },
      { name: "SchuldHulpMaatje Nijmegen", url: "https://schuldhulpmaatje.nl/nijmegen/", type: "Vrijwillige schuldhulp", description: "Vrijwilligers die naast je staan bij het ordenen van je financien." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Nijmegen?", answer: "Loop binnen bij de STIP in je wijk, bel 14 024 of meld je online aan via nijmegen.nl/schulden." },
      { question: "Wat is de STIP?", answer: "STIP staat voor Sociaal Team in de Praktijk. Het is je eerste aanspreekpunt in de wijk voor hulp bij geldzorgen, wonen, werk en gezondheid." },
      { question: "Hoe werkt het armoedebeleid van Nijmegen?", answer: "Nijmegen heeft een ruimhartig beleid: breed pakket aan toeslagen, collectieve zorgverzekering en veel regelingen voor kinderen." },
      { question: "Kan ik ook anoniem advies krijgen?", answer: "Ja, bij de STIP kun je anoniem je situatie bespreken voordat je officieel hulp aanvraagt." },
    ],
    tips: [
      { title: "Meedoen in Nijmegen", description: "Diverse regelingen voor sport, cultuur en scholing voor inwoners met een laag inkomen.", icon: "Trophy" },
      { title: "Voorzieningenwijzer", description: "Check via nijmegen.nl/voorzieningenwijzer welke toeslagen en regelingen voor jou beschikbaar zijn.", icon: "FileText" },
      { title: "Kwijtschelding", description: "Vraag kwijtschelding aan voor gemeentelijke belastingen als je een laag inkomen hebt.", icon: "BadgePercent" },
    ],
    ctaText: "Krijg grip op je rekeningen in Nijmegen",
    gemeenteUrl: "https://www.nijmegen.nl/",
    coordinates: { lat: 51.8126, lng: 5.8372 },
    logoDomain: "nijmegen.nl",
    debtPercentage: 14,
  },

  arnhem: {
    slug: "arnhem",
    name: "Arnhem",
    province: "Gelderland",
    population: "165.000+",
    accentColor: "#E35205",
    accentColorLight: "#FDF0E9",
    accentColorName: "Arnhems oranje",
    unsplashQuery: "Arnhem Netherlands John Frost bridge city",
    unsplashQueryOrgs: "Arnhem Gelderland Netherlands",
    metaTitle: "Schuldhulp Arnhem — Gratis hulp bij schulden",
    metaDescription: "Schulden in Arnhem? Vind gratis schuldhulpverlening via de wijkteams en praktische tips. PayWatch geeft je overzicht.",
    heroTitle: "Schuldhulp in Arnhem",
    heroSubtitle: "Overzicht van hulp bij schulden in Arnhem",
    introTitle: "Schulden in Arnhem: hulp via de wijkteams is laagdrempelig",
    introText: "Arnhem is een groene stad aan de Rijn met een rijke geschiedenis. Maar de stad kent ook wijken waar armoede en schulden deel uitmaken van het straatbeeld. De wijkteams van Arnhem zijn laagdrempelig bereikbaar en helpen je snel op weg naar de juiste hulp.",
    debtContext: "In wijken als Presikhaaf, Malburgen en Klarendal kampen veel huishoudens met schulden. Arnhem heeft een bovengemiddeld percentage inwoners met een bijstandsuitkering. De combinatie van werkloosheid en stijgende vaste lasten maakt veel gezinnen financieel kwetsbaar.",
    localSituation: "De wijkteams van Arnhem zijn je eerste aanspreekpunt. Ze werken nauw samen met Rijnstad voor maatschappelijk werk en de gemeente voor formele schuldhulpverlening.",
    statsHighlight: "Arnhem heeft een van de hoogste percentages bijstandsontvangers van de grote steden",
    organizations: [
      { name: "Wijkteams Arnhem", url: "https://www.wijkteamsarnhem.nl/mijn-vraag/geldzaken/geldzorgen-en-administratie/", type: "Wijkteam", description: "Eerste aanspreekpunt voor geldzorgen. Ze helpen met administratie en verwijzen door naar schuldhulpverlening.", phone: "026 377 3737" },
      { name: "Schuldhulpverlening gemeente Arnhem", url: "https://www.arnhem.nl/product/hulp-bij-geldzorgen/", type: "Gemeentelijke schuldhulp", description: "Formele schuldhulpverlening: intake, schuldregeling en nazorg.", phone: "14 026" },
      { name: "Rijnstad", url: "https://www.rijnstad.nl", type: "Welzijnsorganisatie", description: "Maatschappelijk werk, thuisadministratie en budgetcoaching." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Arnhem?", answer: "Neem contact op met het wijkteam in je buurt of bel 14 026. Je kunt ook online een aanvraag doen." },
      { question: "Heb ik recht op schuldhulp als ik in de bijstand zit?", answer: "Zeker. Juist als bijstandsontvanger heb je recht op hulp. De gemeente kan ook helpen met bijzondere bijstand voor onverwachte kosten." },
      { question: "Kan ik ook hulp krijgen bij het ordenen van mijn post?", answer: "Ja, via Rijnstad kun je thuisadministratie aanvragen. Een vrijwilliger helpt je thuis met het ordenen van je post en administratie." },
      { question: "Wat als ik al loonbeslag heb?", answer: "Ook dan kun je hulp krijgen. Neem zo snel mogelijk contact op zodat de situatie niet verder verslechtert." },
    ],
    tips: [
      { title: "Gelrepas", description: "Korting op sport, cultuur en vervoer voor Arnhemmers met een laag inkomen.", icon: "Ticket" },
      { title: "Bijzondere bijstand", description: "Voor onverwachte noodzakelijke kosten kun je bijzondere bijstand aanvragen bij de gemeente.", icon: "Coins" },
      { title: "Voedselbank Arnhem", description: "Bij de Voedselbank kun je terecht voor gratis boodschappen. Aanmelden via het wijkteam.", icon: "ShoppingCart" },
    ],
    ctaText: "Krijg grip op je rekeningen in Arnhem",
    gemeenteUrl: "https://www.arnhem.nl/product/hulp-bij-geldzorgen/",
    coordinates: { lat: 51.9851, lng: 5.8987 },
    logoDomain: "arnhem.nl",
    debtPercentage: 15,
  },

  haarlem: {
    slug: "haarlem",
    name: "Haarlem",
    province: "Noord-Holland",
    population: "165.000+",
    accentColor: "#C3002F",
    accentColorLight: "#F9E6EB",
    accentColorName: "Haarlems rood",
    unsplashQuery: "Haarlem Netherlands canal Grote Markt",
    unsplashQueryOrgs: "Haarlem city Netherlands",
    metaTitle: "Schuldhulp Haarlem — Gratis hulp bij schulden",
    metaDescription: "Schulden in Haarlem? Ontdek gratis schuldhulpverlening en lokale organisaties. PayWatch helpt met overzicht in je rekeningen.",
    heroTitle: "Schuldhulp in Haarlem",
    heroSubtitle: "Alle hulp bij schulden in de Spaarnestad",
    introTitle: "Schulden in Haarlem: dicht bij Amsterdam, dezelfde druk",
    introText: "Haarlem is een prachtige stad, maar de nabijheid van Amsterdam heeft de woningprijzen flink opgestuwd. Veel Haarlemmers betalen een groot deel van hun inkomen aan woonlasten. De gemeente biedt uitgebreide schuldhulpverlening en werkt samen met het IASZ voor de regio.",
    debtContext: "Door de gespannen woningmarkt in de Randstad zijn ook in Haarlem de woonlasten hoog. In Schalkwijk en delen van Haarlem-Oost zijn de betalingsachterstanden bovengemiddeld. Veel huishoudens balanceren op de rand van financiele problemen.",
    localSituation: "Haarlem werkt met het IASZ (Intergemeentelijke Afdeling Sociale Zaken) voor schuldhulpverlening. De sociale wijkteams zijn het eerste aanspreekpunt in elke buurt.",
    statsHighlight: "In Schalkwijk heeft meer dan 1 op de 6 huishoudens geregistreerde betalingsachterstanden",
    organizations: [
      { name: "IASZ Haarlem", url: "https://www.iasz.nl/hulp-bij-schulden/hulp-bij-schulden-voor-inwoners", type: "Intergemeentelijke sociale dienst", description: "Het IASZ voert schuldhulpverlening uit voor Haarlem en omliggende gemeenten.", phone: "14 023" },
      { name: "Sociaal wijkteam Haarlem", url: "https://www.haarlem.nl/", type: "Wijkteam", description: "Je eerste aanspreekpunt voor geldzorgen. In elke wijk aanwezig." },
      { name: "Humanitas Haarlem", url: "https://www.humanitas.nl/haarlem", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en budgetmaatjes." },
    ],
    faq: [
      { question: "Hoe vraag ik schuldhulp aan in Haarlem?", answer: "Bel 14 023, neem contact op met je wijkteam of meld je online aan via haarlem.nl." },
      { question: "Wat is het IASZ?", answer: "Het Intergemeentelijk samenwerkingsorgaan voert de schuldhulpverlening uit voor Haarlem, Bloemendaal en Heemstede." },
      { question: "Zijn er regelingen voor kinderen?", answer: "Ja, het Kindpakket biedt vergoedingen voor schoolspullen, sport en uitjes." },
      { question: "Hoe lang duurt een traject?", answer: "Een minnelijke schuldregeling duurt 18 tot 36 maanden. Het eerste gesprek is binnen 4 weken." },
    ],
    tips: [
      { title: "Haarlempas", description: "Korting op sport, cultuur en openbaar vervoer voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kindpakket", description: "Vergoedingen voor sport, school en cultuur voor kinderen uit gezinnen met lage inkomens.", icon: "Baby" },
      { title: "Kwijtschelding", description: "Jaarlijks kwijtschelding aanvragen voor gemeentelijke belastingen bij laag inkomen.", icon: "BadgePercent" },
    ],
    ctaText: "Krijg grip op je rekeningen in Haarlem",
    gemeenteUrl: "https://www.haarlem.nl/",
    coordinates: { lat: 52.3874, lng: 4.6462 },
    logoDomain: "haarlem.nl",
    debtPercentage: 12,
  },

  enschede: {
    slug: "enschede",
    name: "Enschede",
    province: "Overijssel",
    population: "160.000+",
    accentColor: "#D4213D",
    accentColorLight: "#FBEAED",
    accentColorName: "Enschedees rood",
    unsplashQuery: "Enschede Netherlands Twente city",
    unsplashQueryOrgs: "Enschede Overijssel Netherlands",
    metaTitle: "Schuldhulp Enschede — Gratis hulp bij schulden",
    metaDescription: "Schulden in Enschede? Vind gratis schuldhulpverlening en hulporganisaties. PayWatch helpt je met overzicht in je rekeningen.",
    heroTitle: "Schuldhulp in Enschede",
    heroSubtitle: "Alle hulp bij schulden in de Twentse hoofdstad",
    introTitle: "Schulden in Enschede: Twentse mentaliteit, concrete hulp",
    introText: "Enschede is het hart van Twente. Na het verdwijnen van de textielindustrie heeft de stad zich heruitgevonden, maar niet iedereen heeft deze transitie meegemaakt. De gemeente Enschede biedt uitgebreide schuldhulpverlening en werkt samen met de Stadsbank Oost Nederland.",
    debtContext: "In wijken als Velve-Lindenhof, Wesselerbrink en Deppenbroek is het percentage huishoudens met schulden bovengemiddeld. Enschede kent een relatief hoge werkloosheid en veel inwoners met een laag inkomen. De textielcrisis van decennia geleden werkt nog steeds door.",
    localSituation: "Enschede werkt met wijkcoaches als eerste aanspreekpunt en de Stadsbank Oost Nederland voor formele schuldhulpverlening. Er is een breed pakket aan minimaregelingen.",
    statsHighlight: "Enschede heeft een van de hoogste armoedecijfers van Oost-Nederland",
    organizations: [
      { name: "Stadsbank Oost Nederland", url: "https://son.nl", type: "Stadsbank", description: "Formele schuldhulpverlening voor Enschede en regio: schuldregelingen, budgetbeheer en kredieten.", phone: "053 480 5800" },
      { name: "Wijkcoaches Enschede", url: "https://www.enschede.nl/", type: "Gemeentelijk wijkteam", description: "Wijkcoaches zijn je eerste aanspreekpunt voor geldzorgen in Enschede." },
      { name: "Humanitas Twente", url: "https://www.humanitas.nl/twente", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en budgetcoaching door getrainde vrijwilligers." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Enschede?", answer: "Neem contact op met een wijkcoach of bel de Stadsbank Oost Nederland op 053 480 5800." },
      { question: "Wat doet de Stadsbank Oost Nederland?", answer: "De Stadsbank regelt schuldregelingen, biedt budgetbeheer en verstrekt sociale kredieten voor noodzakelijke uitgaven." },
      { question: "Zijn er minimaregelingen in Enschede?", answer: "Ja, Enschede heeft een ruim pakket: individuele inkomenstoeslag, collectieve zorgverzekering en regelingen voor kinderen." },
      { question: "Kan ik ook anoniem advies krijgen?", answer: "Ja, bij de wijkcoach kun je vrijblijvend je situatie bespreken." },
    ],
    tips: [
      { title: "Enschedepas", description: "Korting op sport, cultuur en vervoer voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding", description: "Kwijtschelding van gemeentelijke belastingen bij laag inkomen.", icon: "BadgePercent" },
      { title: "Voedselbank Enschede", description: "Gratis boodschappen via de Voedselbank. Aanmelden via de wijkcoach.", icon: "ShoppingCart" },
    ],
    ctaText: "Krijg grip op je rekeningen in Enschede",
    gemeenteUrl: "https://www.enschede.nl/",
    coordinates: { lat: 52.2215, lng: 6.8937 },
    logoDomain: "enschede.nl",
    debtPercentage: 14,
  },

  zaanstad: {
    slug: "zaanstad",
    name: "Zaanstad",
    province: "Noord-Holland",
    population: "157.000+",
    accentColor: "#00693E",
    accentColorLight: "#E6F2EC",
    accentColorName: "Zaans groen",
    unsplashQuery: "Zaandam Netherlands Zaanse Schans windmills",
    unsplashQueryOrgs: "Zaandam city Netherlands",
    metaTitle: "Schuldhulp Zaanstad — Gratis hulp bij schulden",
    metaDescription: "Schulden in Zaanstad? Ontdek gratis schuldhulpverlening en hulporganisaties. PayWatch helpt je met grip op je rekeningen.",
    heroTitle: "Schuldhulp in Zaanstad",
    heroSubtitle: "Alle hulp bij schulden in de Zaanstreek",
    introTitle: "Schulden in Zaanstad: groeiende stad, groeiende uitdagingen",
    introText: "Zaanstad, met Zaandam als centrumstad, groeit snel door de nabijheid van Amsterdam. Veel Amsterdammers zijn naar de Zaanstreek verhuisd voor betaalbare woningen, maar ook hier stijgen de kosten. De gemeente biedt schuldhulpverlening via de sociale wijkteams.",
    debtContext: "Door de instroom vanuit Amsterdam zijn de woningprijzen in Zaanstad fors gestegen. In Zaandam-Zuid en Poelenburg hebben relatief veel huishoudens te maken met betalingsachterstanden. De diverse bevolking vraagt om meertalige en cultuursensitieve hulpverlening.",
    localSituation: "Zaanstad werkt met sociale wijkteams en het Sociaal Wijkteam Zaanstad als coorderend orgaan. Er is aandacht voor preventie en vroegsignalering via samenwerkingen met woningcorporaties en nutsbedrijven.",
    statsHighlight: "Zaanstad telt naar schatting 8.000 huishoudens met risicovolle schulden",
    organizations: [
      { name: "Schuldhulpverlening gemeente Zaanstad", url: "https://www.zaanstad.nl/", type: "Gemeentelijke schuldhulp", description: "De gemeente Zaanstad biedt volledige schuldhulpverlening. Aanmelden via het sociaal wijkteam of telefonisch.", phone: "14 075" },
      { name: "Sociaal Wijkteam Zaanstad", url: "https://www.zaanstad.nl/", type: "Wijkteam", description: "Eerste aanspreekpunt voor geldzorgen in je buurt." },
      { name: "Humanitas Zaanstreek", url: "https://www.humanitas.nl/zaanstreek", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en budgetmaatjes door vrijwilligers." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Zaanstad?", answer: "Bel 14 075, neem contact op met het sociaal wijkteam of meld je online aan via zaanstad.nl." },
      { question: "Is er meertalige hulp beschikbaar?", answer: "Ja, Zaanstad biedt hulp met tolken en er zijn organisaties die in meerdere talen kunnen helpen." },
      { question: "Hoe werkt vroegsignalering?", answer: "De gemeente ontvangt signalen van nutsbedrijven en woningcorporaties en biedt proactief hulp aan." },
      { question: "Wat als ik net vanuit Amsterdam ben verhuisd?", answer: "Als je ingeschreven staat in Zaanstad, heb je recht op schuldhulpverlening via de gemeente Zaanstad." },
    ],
    tips: [
      { title: "Zaanpas", description: "Korting op sport, cultuur en uitjes voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding", description: "Kwijtschelding van gemeentelijke belastingen bij laag inkomen.", icon: "BadgePercent" },
      { title: "Kindregelingen", description: "Vergoedingen voor schoolkosten, sport en cultuur voor kinderen.", icon: "Baby" },
    ],
    ctaText: "Krijg grip op je rekeningen in Zaanstad",
    gemeenteUrl: "https://www.zaanstad.nl/",
    coordinates: { lat: 52.4388, lng: 4.8267 },
    logoDomain: "zaanstad.nl",
    debtPercentage: 11,
  },

  amersfoort: {
    slug: "amersfoort",
    name: "Amersfoort",
    province: "Utrecht",
    population: "160.000+",
    accentColor: "#004B87",
    accentColorLight: "#E6EFF7",
    accentColorName: "Amersfoorts blauw",
    unsplashQuery: "Amersfoort Netherlands Koppelpoort medieval city",
    unsplashQueryOrgs: "Amersfoort Utrecht Netherlands",
    metaTitle: "Schuldhulp Amersfoort — Gratis hulp bij schulden",
    metaDescription: "Schulden in Amersfoort? Vind gratis schuldhulpverlening via Stadsring en praktische tips. PayWatch geeft je overzicht.",
    heroTitle: "Schuldhulp in Amersfoort",
    heroSubtitle: "Alle hulp bij schulden in Amersfoort",
    introTitle: "Schulden in Amersfoort: in een welvarende stad vallen sommigen buiten de boot",
    introText: "Amersfoort is een van de snelst groeiende steden van Nederland. De middeleeuwse binnenstad contrasteert met moderne nieuwbouwwijken. Maar ook hier zijn er inwoners die worstelen met schulden. Stadsring speelt een centrale rol in de schuldhulpverlening.",
    debtContext: "Hoewel Amersfoort over het geheel genomen een welvarende stad is, zijn er wijken zoals Liendert, Randenbroek en Schuilenburg waar de armoede en schuldenproblematiek bovengemiddeld zijn. De hoge woningprijzen maken het voor starters en lagere inkomens lastig.",
    localSituation: "Amersfoort werkt samen met Stadsring voor schuldhulpverlening. De sociale wijkteams zijn het eerste aanspreekpunt. Er is extra aandacht voor preventie via het programma 'Financieel Gezond'.",
    statsHighlight: "Amersfoort telt naar schatting 6.000 huishoudens met problematische schulden",
    organizations: [
      { name: "Stadsring", url: "https://stadsring.nl/", type: "Regionale schuldhulporganisatie", description: "Stadsring voert schuldhulpverlening uit voor Amersfoort en regio: intake, schuldregelingen, budgetbeheer en nazorg.", phone: "033 460 8260" },
      { name: "Sociaal wijkteam Amersfoort", url: "https://www.amersfoort.nl/", type: "Wijkteam", description: "Eerste aanspreekpunt voor geldzorgen in je buurt." },
      { name: "SchuldHulpMaatje Amersfoort", url: "https://schuldhulpmaatje.nl/amersfoort/", type: "Vrijwillige schuldhulp", description: "Persoonlijke begeleiding door vrijwilligers bij het ordenen van je financien." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Amersfoort?", answer: "Neem contact op met Stadsring (033 460 8260) of het sociaal wijkteam in je wijk." },
      { question: "Wat doet Stadsring precies?", answer: "Stadsring verzorgt de complete schuldhulpverlening: van het eerste gesprek tot de schuldregeling en nazorg erna." },
      { question: "Is er hulp voor senioren?", answer: "Ja, Amersfoort heeft speciale aandacht voor ouderen met schulden. Stadsring biedt ook huisbezoeken." },
      { question: "Hoe lang duurt een schuldhulptraject?", answer: "Een minnelijke schuldregeling duurt 18 tot 36 maanden. Het eerste gesprek is binnen 4 weken." },
    ],
    tips: [
      { title: "Gelrepas / Amersfoortpas", description: "Korting op sport, cultuur en vervoer voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding", description: "Kwijtschelding van gemeentelijke belastingen. Vraag het jaarlijks aan via amersfoort.nl.", icon: "BadgePercent" },
      { title: "Financieel Gezond", description: "Preventieproject van de gemeente: gratis workshops en coaching om schulden te voorkomen.", icon: "GraduationCap" },
    ],
    ctaText: "Krijg grip op je rekeningen in Amersfoort",
    gemeenteUrl: "https://www.amersfoort.nl/hulp-bij-schulden-en-geldzaken",
    coordinates: { lat: 52.1561, lng: 5.3878 },
    logoDomain: "amersfoort.nl",
    debtPercentage: 9,
  },
  apeldoorn: {
    slug: "apeldoorn",
    name: "Apeldoorn",
    province: "Gelderland",
    population: "165.000+",
    accentColor: "#E30613",
    accentColorLight: "#FDE8EA",
    accentColorName: "Apeldoorns rood",
    unsplashQuery: "Apeldoorn Netherlands Veluwe forest",
    unsplashQueryOrgs: "Apeldoorn Netherlands city center",
    metaTitle: "Schuldhulp Apeldoorn — Gratis hulp bij schulden in Apeldoorn",
    metaDescription: "Schulden in Apeldoorn? Via Samen055 krijg je gratis hulp bij geldzorgen. Ontdek hoe PayWatch je helpt om incassokosten te voorkomen.",
    heroTitle: "Schuldhulp in Apeldoorn",
    heroSubtitle: "Overzicht van alle hulp bij schulden op de Veluwe",
    introTitle: "Schulden in Apeldoorn: hulp ligt dichterbij dan je denkt",
    introText: "Apeldoorn is een groene stad met een warm karakter. Maar ook hier lopen mensen vast op onbetaalde rekeningen, hoge energienota's of een plotseling inkomensverlies. De gemeente Apeldoorn heeft met Samen055 een laagdrempelig loket waar je terechtkunt voordat kleine schulden grote problemen worden.",
    debtContext: "Als grootste gemeente op de Veluwe kent Apeldoorn een mix van stedelijke en landelijke problemen. In wijken als De Maten en Zevenhuizen spelen betalingsachterstanden vaker dan gemiddeld. De afstand tot voorzieningen in het buitengebied maakt het extra belangrijk dat hulp digitaal bereikbaar is.",
    localSituation: "Apeldoorn zet in op vroegsignalering via energiebedrijven en woningcorporaties. Samen055 fungeert als centraal aanspreekpunt voor alle hulpvragen, van schulden tot opvoeding. Die brede aanpak voorkomt dat mensen van het kastje naar de muur worden gestuurd.",
    statsHighlight: "In Apeldoorn heeft circa 8% van de huishoudens problematische schulden",
    organizations: [
      { name: "Samen055", url: "https://www.apeldoorn.nl/werken-en-leren/geldzorgen/hulp-bij-geldzorgen-of-schulden/schuldhulpverlening.html", type: "Gemeentelijk samenwerkingsloket", description: "Het centrale loket van Apeldoorn voor alle hulpvragen. Ze helpen met budgetcoaching, schuldbemiddeling en doorverwijzing naar specialisten.", phone: "055 357 8200" },
      { name: "SchuldHulpMaatje Apeldoorn", url: "https://schuldhulpmaatje.nl/apeldoorn/", type: "Vrijwillige schuldhulp", description: "Vrijwilligers die naast je staan bij het ordenen van je administratie en meegaan naar gesprekken." },
      { name: "Humanitas Apeldoorn", url: "https://www.humanitas.nl/", type: "Maatschappelijke ondersteuning", description: "Thuisadministratie en budgetbegeleiding voor inwoners die moeite hebben met hun papierwerk." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Apeldoorn?", answer: "Bel Samen055 op 055 357 8200 of loop binnen bij het gemeentehuis. Het eerste gesprek is altijd gratis." },
      { question: "Wat is Samen055?", answer: "Samen055 is het centrale loket van de gemeente Apeldoorn voor hulp bij geldzorgen, opvoeding, wonen en werk. Eén telefoontje is genoeg." },
      { question: "Hoe lang duurt schuldhulp in Apeldoorn?", answer: "Het eerste gesprek vindt binnen 4 weken plaats. Een schuldregeling duurt meestal 18 tot 36 maanden." },
      { question: "Is er hulp voor jongeren?", answer: "Ja, Apeldoorn heeft speciale trajecten voor jongeren tot 27 jaar met schulden. Vraag ernaar bij Samen055." },
    ],
    tips: [
      { title: "Apeldoornpas", description: "Korting op sport, cultuur en zwemmen voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding belastingen", description: "Kwijtschelding van gemeentelijke belastingen voor lage inkomens. Aanvragen via apeldoorn.nl.", icon: "BadgePercent" },
      { title: "Energietoeslag", description: "Extra toeslag voor huishoudens die moeite hebben met de energierekening.", icon: "Zap" },
    ],
    ctaText: "Krijg grip op je rekeningen in Apeldoorn",
    gemeenteUrl: "https://www.apeldoorn.nl/werken-en-leren/geldzorgen/hulp-bij-geldzorgen-of-schulden/schuldhulpverlening.html",
    coordinates: { lat: 52.2112, lng: 5.9699 },
    logoDomain: "apeldoorn.nl",
    debtPercentage: 8,
  },
  leiden: {
    slug: "leiden",
    name: "Leiden",
    province: "Zuid-Holland",
    population: "130.000+",
    accentColor: "#CC0000",
    accentColorLight: "#FCE4E4",
    accentColorName: "Leids rood",
    unsplashQuery: "Leiden Netherlands canals university",
    unsplashQueryOrgs: "Leiden Netherlands historic center",
    metaTitle: "Schuldhulp Leiden — Gratis hulp bij schulden in Leiden",
    metaDescription: "Schulden in Leiden? De Stadsbank Leiden helpt je gratis met schuldsanering en budgetcoaching. Ontdek hoe PayWatch je rekeningen bewaakt.",
    heroTitle: "Schuldhulp in Leiden",
    heroSubtitle: "Overzicht van alle hulp bij schulden in de Sleutelstad",
    introTitle: "Schulden in Leiden: de Sleutelstad helpt",
    introText: "Leiden is een universiteitsstad met een rijke geschiedenis, maar ook studenten, zzp'ers en gezinnen lopen hier vast op schulden. De stad heeft met de Stadsbank Leiden een ervaren organisatie die al tientallen jaren schuldhulp biedt. Daarnaast zijn er diverse vrijwilligersorganisaties actief.",
    debtContext: "De hoge huurprijzen in het centrum en wijken als de Stevenshof en Merenwijk, gecombineerd met een groot aandeel studenten en flexwerkers, maken Leiden kwetsbaar voor betalingsachterstanden. Vooral de overgang van studie naar werk is een risicomoment.",
    localSituation: "Leiden werkt samen met de regio (Leiderdorp, Oegstgeest, Zoeterwoude) via de Stadsbank. Dat betekent dat ook inwoners van omliggende gemeenten hier terecht kunnen. De gemeente heeft een actief vroegsignaleringsprogramma via woningcorporaties en zorgverzekeraars.",
    statsHighlight: "De Stadsbank Leiden helpt jaarlijks meer dan 2.000 inwoners met schulden",
    organizations: [
      { name: "Stadsbank Leiden", url: "https://gemeente.leiden.nl/inwoners-en-ondernemers/uitkering-en-inkomen/hulp-bij-schulden/schuldhulpverlening/", type: "Stadsbank / kredietbank", description: "De Stadsbank biedt schuldhulpverlening, budgetbeheer, beschermingsbewind en sociale kredieten. Ze zijn het officiële loket voor de hele regio.", phone: "071 516 5109" },
      { name: "SchuldHulpMaatje Leiden", url: "https://schuldhulpmaatje.nl/leiden/", type: "Vrijwillige schuldhulp", description: "Persoonlijke begeleiding door getrainde vrijwilligers bij het ordenen van je financien." },
      { name: "Humanitas Leiden", url: "https://www.humanitas.nl/", type: "Maatschappelijke ondersteuning", description: "Thuisadministratie en formulierenhulp voor inwoners die moeite hebben met de bureaucratie." },
    ],
    faq: [
      { question: "Hoe vraag ik schuldhulp aan in Leiden?", answer: "Neem contact op met de Stadsbank Leiden (071 516 5109) of meld je aan via de website van de gemeente." },
      { question: "Kan ik als student schuldhulp krijgen?", answer: "Ja, ook studenten met schulden kunnen terecht bij de Stadsbank. Ze helpen ook met DUO-schulden en studiefinanciering." },
      { question: "Is de Stadsbank ook voor Leiderdorp?", answer: "Ja, de Stadsbank Leiden bedient ook Leiderdorp, Oegstgeest en Zoeterwoude." },
      { question: "Hoe lang duurt het eerste gesprek?", answer: "Het intakegesprek duurt ongeveer een uur. Je krijgt binnen 4 weken een afspraak." },
    ],
    tips: [
      { title: "Leidenpas", description: "Korting op cultuur, sport en vervoer voor Leidenaren met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding", description: "Kwijtschelding van waterschaps- en gemeentelijke belastingen bij laag inkomen.", icon: "BadgePercent" },
      { title: "Formulierenteam", description: "Hulp bij het invullen van formulieren voor toeslagen, belasting en aanvragen.", icon: "FileText" },
    ],
    ctaText: "Krijg grip op je rekeningen in Leiden",
    gemeenteUrl: "https://gemeente.leiden.nl/inwoners-en-ondernemers/uitkering-en-inkomen/hulp-bij-schulden/schuldhulpverlening/",
    coordinates: { lat: 52.1601, lng: 4.4970 },
    logoDomain: "leiden.nl",
    debtPercentage: 9,
  },
  dordrecht: {
    slug: "dordrecht",
    name: "Dordrecht",
    province: "Zuid-Holland",
    population: "120.000+",
    accentColor: "#003DA5",
    accentColorLight: "#E6EDF8",
    accentColorName: "Dordts blauw",
    unsplashQuery: "Dordrecht Netherlands old town harbor",
    unsplashQueryOrgs: "Dordrecht Netherlands waterfront",
    metaTitle: "Schuldhulp Dordrecht — Gratis hulp bij schulden in Dordrecht",
    metaDescription: "Schulden in Dordrecht? De Sociale Dienst Drechtsteden helpt gratis. Ontdek hoe PayWatch je waarschuwt voordat een rekening escaleert.",
    heroTitle: "Schuldhulp in Dordrecht",
    heroSubtitle: "Overzicht van alle hulp bij schulden in de Drechtsteden",
    introTitle: "Schulden in Dordrecht: hulp via de Drechtsteden",
    introText: "Dordrecht, de oudste stad van Holland, kent dezelfde financiele uitdagingen als andere grote steden. De Sociale Dienst Drechtsteden is het regionale loket waar inwoners van Dordrecht, Zwijndrecht, Sliedrecht, Papendrecht, Hendrik-Ido-Ambacht en Alblasserdam terecht kunnen voor schuldhulp.",
    debtContext: "In de Drechtsteden wonen relatief veel gezinnen met een modaal inkomen die door onverwachte kosten in de problemen komen. De combinatie van hoge energielasten in oudere woningen en stijgende zorgkosten raakt deze groep hard. Vooral in Dordrecht-West en Crabbehof spelen betalingsachterstanden.",
    localSituation: "Dordrecht werkt regionaal samen via de Sociale Dienst Drechtsteden. Een voordeel: je hoeft maar bij een loket aan te kloppen voor de hele regio. De gemeente investeert ook in preventie via het programma Financieel Fit.",
    statsHighlight: "De Drechtsteden helpen jaarlijks ruim 1.500 huishoudens met schuldhulp",
    organizations: [
      { name: "Sociale Dienst Drechtsteden", url: "https://cms.dordrecht.nl/Inwoners/Overzicht_Inwoners/Zorg_en_ondersteuning/hulp_bij_geldzaken", type: "Sociale dienst", description: "Het regionale loket voor schuldhulpverlening in de Drechtsteden. Ze bieden intake, budgetcoaching en schuldregelingen.", phone: "078 770 8000" },
      { name: "Humanitas Drechtsteden", url: "https://www.humanitas.nl/", type: "Vrijwillige ondersteuning", description: "Thuisadministratie en budgetbegeleiding door vrijwilligers. Laagdrempelig en gratis." },
      { name: "Schuldhulpmaatje Dordrecht", url: "https://schuldhulpmaatje.nl/dordrecht/", type: "Vrijwillige schuldhulp", description: "Getrainde vrijwilligers die naast je staan bij het oplossen van je schulden." },
    ],
    faq: [
      { question: "Waar meld ik me aan voor schuldhulp in Dordrecht?", answer: "Neem contact op met de Sociale Dienst Drechtsteden via 078 770 8000 of via de website van de gemeente." },
      { question: "Geldt de hulp ook voor Zwijndrecht?", answer: "Ja, de Sociale Dienst Drechtsteden bedient Dordrecht, Zwijndrecht, Sliedrecht, Papendrecht, Hendrik-Ido-Ambacht en Alblasserdam." },
      { question: "Wat kost schuldhulpverlening?", answer: "Niets. Schuldhulpverlening via de gemeente is altijd gratis voor inwoners." },
      { question: "Hoe snel kan ik terecht?", answer: "Het eerste gesprek wordt binnen 4 weken ingepland. Bij acute situaties (dreigende huisuitzetting) kun je sneller terecht." },
    ],
    tips: [
      { title: "Dordtpas", description: "Korting op sport, cultuur en vervoer voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Financieel Fit", description: "Gratis workshops en coaching om financieel weerbaar te worden.", icon: "GraduationCap" },
      { title: "Kwijtschelding", description: "Kwijtschelding van lokale belastingen bij een laag inkomen.", icon: "BadgePercent" },
    ],
    ctaText: "Krijg grip op je rekeningen in Dordrecht",
    gemeenteUrl: "https://cms.dordrecht.nl/Inwoners/Overzicht_Inwoners/Zorg_en_ondersteuning/hulp_bij_geldzaken",
    coordinates: { lat: 51.8133, lng: 4.6901 },
    logoDomain: "dordrecht.nl",
    debtPercentage: 10,
  },
  maastricht: {
    slug: "maastricht",
    name: "Maastricht",
    province: "Limburg",
    population: "122.000+",
    accentColor: "#E2001A",
    accentColorLight: "#FCE4E7",
    accentColorName: "Maastrichts rood",
    unsplashQuery: "Maastricht Netherlands Vrijthof square",
    unsplashQueryOrgs: "Maastricht Netherlands Meuse river",
    metaTitle: "Schuldhulp Maastricht — Gratis hulp bij schulden in Maastricht",
    metaDescription: "Schulden in Maastricht? De Kredietbank Limburg helpt gratis met schuldsanering. Ontdek hoe PayWatch je rekeningen bewaakt en incassokosten voorkomt.",
    heroTitle: "Schuldhulp in Maastricht",
    heroSubtitle: "Overzicht van alle hulp bij schulden in Limburg",
    introTitle: "Schulden in Maastricht: je staat er niet alleen voor",
    introText: "Maastricht is een stad van levendigheid en cultuur. Maar achter de gevels van de Maas worstelen veel inwoners met schulden. De Kredietbank Limburg is het regionale expertisecentrum en helpt jaarlijks duizenden Limburgers met het oplossen van financiele problemen.",
    debtContext: "Limburg kent relatief hoge werkloosheid en veel huishoudens met een laag inkomen, vooral in de oude mijnstreek en de buitenwijken van Maastricht. De vergrijzing en het hoge percentage alleenstaanden maken de regio extra kwetsbaar voor schuldenproblematiek.",
    localSituation: "Maastricht heeft een Team Vroegsignalering dat actief contact opneemt met inwoners die betalingsachterstanden oplopen bij woningcorporaties, energiebedrijven en zorgverzekeraars. Je kunt dus hulp krijgen nog voordat je er zelf om vraagt.",
    statsHighlight: "De Kredietbank Limburg behandelt jaarlijks meer dan 3.000 schulddossiers",
    organizations: [
      { name: "Kredietbank Limburg", url: "https://www.gemeentemaastricht.nl/teamvroegsignalering", type: "Kredietbank", description: "De Kredietbank Limburg biedt schuldhulpverlening, budgetbeheer en sociale kredieten voor inwoners van heel Limburg.", phone: "043 350 5050" },
      { name: "Team Vroegsignalering", url: "https://www.gemeentemaastricht.nl/teamvroegsignalering", type: "Gemeentelijk preventieteam", description: "Dit team neemt proactief contact op met inwoners die betalingsachterstanden hebben. Je hoeft zelf niet de eerste stap te zetten." },
      { name: "SchuldHulpMaatje Maastricht", url: "https://schuldhulpmaatje.nl/maastricht/", type: "Vrijwillige schuldhulp", description: "Vrijwilligers die je persoonlijk begeleiden bij het op orde brengen van je financien." },
    ],
    faq: [
      { question: "Hoe meld ik me aan voor schuldhulp in Maastricht?", answer: "Bel de Kredietbank Limburg op 043 350 5050 of meld je aan via de website van de gemeente Maastricht." },
      { question: "Wat is het Team Vroegsignalering?", answer: "Een gemeentelijk team dat actief inwoners benadert die betalingsachterstanden hebben. Ze nemen contact met je op, niet andersom." },
      { question: "Helpt de Kredietbank ook in andere Limburgse gemeenten?", answer: "Ja, de Kredietbank Limburg bedient alle 31 Limburgse gemeenten." },
      { question: "Kan ik anoniem informatie krijgen?", answer: "Ja, je kunt vrijblijvend bellen met de Kredietbank voor informatie zonder je naam te hoeven geven." },
    ],
    tips: [
      { title: "Maastrichtpas (U-Pas)", description: "Korting op sport, cultuur en openbaar vervoer bij een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding belastingen", description: "Kwijtschelding van gemeentelijke en waterschapsbelastingen bij een laag inkomen.", icon: "BadgePercent" },
      { title: "Voedselbank Maastricht", description: "Gratis voedselpakketten voor inwoners die tijdelijk niet genoeg hebben voor boodschappen.", icon: "ShoppingBag" },
    ],
    ctaText: "Krijg grip op je rekeningen in Maastricht",
    gemeenteUrl: "https://www.gemeentemaastricht.nl/teamvroegsignalering",
    coordinates: { lat: 50.8514, lng: 5.6910 },
    logoDomain: "maastricht.nl",
    debtPercentage: 11,
  },
  "s-hertogenbosch": {
    slug: "s-hertogenbosch",
    name: "'s-Hertogenbosch",
    province: "Noord-Brabant",
    population: "160.000+",
    accentColor: "#1D428A",
    accentColorLight: "#E8EDF5",
    accentColorName: "Boschs blauw",
    unsplashQuery: "s-Hertogenbosch Netherlands Den Bosch cathedral",
    unsplashQueryOrgs: "Den Bosch Netherlands medieval city",
    metaTitle: "Schuldhulp 's-Hertogenbosch — Gratis hulp bij schulden in Den Bosch",
    metaDescription: "Schulden in 's-Hertogenbosch? Eerste Hulp Bij Geldzaken helpt gratis. Ontdek hoe PayWatch je waarschuwt voordat rekeningen escaleren.",
    heroTitle: "Schuldhulp in 's-Hertogenbosch",
    heroSubtitle: "Overzicht van alle hulp bij schulden in Den Bosch",
    introTitle: "Schulden in Den Bosch: de gemeente helpt je verder",
    introText: "'s-Hertogenbosch, of gewoon Den Bosch, staat bekend om zijn Bourgondische karakter. Maar ook Bosschenaren lopen vast op schulden. De gemeente heeft met Eerste Hulp Bij Geldzaken een laagdrempelig loket opgezet waar inwoners snel en zonder wachttijden terecht kunnen.",
    debtContext: "Den Bosch heeft een gevarieerde bevolking: van studenten aan Avans en HAS tot gezinnen in de buitenwijken. De stijgende woonlasten in wijken als de Gestelse Buurt en Rosmalen, gecombineerd met hoge zorgkosten, zorgen voor een groeiend aantal inwoners met betalingsproblemen.",
    localSituation: "'s-Hertogenbosch onderscheidt zich met het concept Eerste Hulp Bij Geldzaken: een walk-in spreekuur waar je zonder afspraak terecht kunt. Dat verlaagt de drempel enorm. Daarnaast werkt de gemeente samen met woningcorporaties aan vroegsignalering.",
    statsHighlight: "Eerste Hulp Bij Geldzaken helpt jaarlijks meer dan 1.000 Bosschenaren",
    organizations: [
      { name: "Eerste Hulp Bij Geldzaken", url: "https://www.s-hertogenbosch.nl/product/schulddienstverlening/", type: "Gemeentelijke lokale hulp", description: "Laagdrempelig loket met inloopspreekuur. Je kunt zonder afspraak binnenlopen voor hulp bij schulden, budgetproblemen of aanvragen.", phone: "073 615 5155" },
      { name: "SchuldHulpMaatje Den Bosch", url: "https://schuldhulpmaatje.nl/s-hertogenbosch/", type: "Vrijwillige schuldhulp", description: "Vrijwillige budgetcoaches die je stap voor stap helpen bij het ordenen van je financien." },
      { name: "Humanitas Den Bosch", url: "https://www.humanitas.nl/", type: "Maatschappelijke ondersteuning", description: "Thuisadministratie en formulierenhulp voor inwoners die vastlopen op papierwerk." },
    ],
    faq: [
      { question: "Hoe krijg ik schuldhulp in Den Bosch?", answer: "Loop binnen bij Eerste Hulp Bij Geldzaken (zonder afspraak) of bel 073 615 5155." },
      { question: "Wat is Eerste Hulp Bij Geldzaken?", answer: "Een inloopspreekuur van de gemeente waar je zonder afspraak terecht kunt voor hulp bij geldzorgen. Gratis en laagdrempelig." },
      { question: "Kan ik ook online hulp krijgen?", answer: "Ja, via de website van de gemeente kun je een aanvraag indienen. Maar het inloopspreekuur is vaak sneller." },
      { question: "Hoe lang duurt een schuldhulptraject?", answer: "Een minnelijk traject duurt 18 tot 36 maanden. Het eerste gesprek is binnen 4 weken, bij het inloopspreekuur dezelfde dag." },
    ],
    tips: [
      { title: "Stadspas Den Bosch", description: "Korting op sport, cultuur en evenementen voor inwoners met een laag inkomen.", icon: "Ticket" },
      { title: "Kwijtschelding", description: "Kwijtschelding van gemeentelijke belastingen. Aanvragen via s-hertogenbosch.nl.", icon: "BadgePercent" },
      { title: "Buurtteams", description: "Ondersteuning dicht bij huis voor geldzorgen, opvoeding en gezondheid.", icon: "Users" },
    ],
    ctaText: "Krijg grip op je rekeningen in Den Bosch",
    gemeenteUrl: "https://www.s-hertogenbosch.nl/product/schulddienstverlening/",
    coordinates: { lat: 51.6978, lng: 5.3037 },
    logoDomain: "s-hertogenbosch.nl",
    debtPercentage: 9,
  },
};

/* ── Helper: get city by slug ── */
export function getCityBySlug(slug: string): CityPage | undefined {
  return cityPages[slug as CitySlug];
}

/* ── All city pages as array ── */
export function getAllCityPages(): CityPage[] {
  return Object.values(cityPages);
}
