/* Auto-generated from Excel data — do not edit manually */
/* 335 gemeenten, 150 advocaten, 43 seed organizations */

export interface GemeenteData {
  gemeente: string;
  url: string;
  partner: string;
  partnerUrl: string;
  /* From seed list (43 cities only) */
  orgName?: string;
  orgUrl?: string;
  orgType?: string;
  note?: string;
}

export const GEMEENTE_DATA: GemeenteData[] = [
  {gemeente:"Aa en Hunze",url:"https://www.aaenhunze.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Aalsmeer",url:"https://www.aalsmeer.nl/schuldhulpverlening",partner:"Kredietbank Amsterdam",partnerUrl:"https://www.amsterdam.nl/schuldhulp"},
  {gemeente:"Aalten",url:"https://www.aalten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Achtkarspelen",url:"https://www.achtkarspelen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Alblasserdam",url:"https://www.alblasserdam.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Albrandswaard",url:"https://www.albrandswaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Alkmaar",url:"https://www.alkmaar.nl/direct-regelen/werk-en-inkomen/geldzorgen-en-uitkering/betalingsachterstand-geldzorgen-of-schulden/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Almelo",url:"https://www.almelo.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Almere",url:"https://www.almere.nl/werk-en-inkomen/schulden",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Verder",orgUrl:"https://www.verdergroep.nl/schuldhulpverlening-aanvragen/",orgType:"uitvoerende schuldhulporganisatie"},
  {gemeente:"Alphen aan den Rijn",url:"https://www.alphenaandenrijn.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Alphen-Chaam",url:"https://www.alphenchaam.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Altena",url:"https://www.altena.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Ameland",url:"https://www.ameland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Amersfoort",url:"https://www.amersfoort.nl/hulp-bij-schulden-en-geldzaken",partner:"Stadsring",partnerUrl:"https://stadsring.nl",orgName:"Stadsring",orgUrl:"https://stadsring.nl/",orgType:"regionale schuldhulporganisatie"},
  {gemeente:"Amstelveen",url:"https://www.amstelveen.nl/schuldhulpverlening",partner:"Kredietbank Amsterdam",partnerUrl:"https://www.amsterdam.nl/schuldhulp"},
  {gemeente:"Amsterdam",url:"https://www.amsterdam.nl/werk-en-inkomen/regelingen-bij-laag-inkomen-pak-je-kans/schuldhulpverlening/",partner:"Kredietbank Amsterdam",partnerUrl:"https://www.amsterdam.nl/schuldhulp",orgName:"Buurtteam Amsterdam",orgUrl:"https://www.buurtteamamsterdam.nl/hulp-bij-schulden-amsterdam/",orgType:"buurtteam / lokale hulp"},
  {gemeente:"Apeldoorn",url:"https://www.apeldoorn.nl/werken-en-leren/geldzorgen/hulp-bij-geldzorgen-of-schulden/schuldhulpverlening.html",partner:"Stadsbank Apeldoorn",partnerUrl:"https://www.apeldoorn.nl/stadsbank",orgName:"Samen055",orgUrl:"https://www.samen055.nl/rondkomen/hulp-bij-geldzorgen-of-schulden.html",orgType:"gemeentelijk samenwerkingsloket"},
  {gemeente:"Arnhem",url:"https://www.arnhem.nl/product/hulp-bij-geldzorgen/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Wijkteams Arnhem",orgUrl:"https://www.wijkteamsarnhem.nl/mijn-vraag/geldzaken/geldzorgen-en-administratie/",orgType:"wijkteam / lokale hulp"},
  {gemeente:"Assen",url:"https://www.assen.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Asten",url:"https://www.asten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Baarle-Nassau",url:"https://www.baarlenassau.nl/schuldhulpverlening",partner:"Kredietbank Rotterdam",partnerUrl:"N/A"},
  {gemeente:"Baarn",url:"https://www.baarn.nl/stadsring",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Stadsring",orgUrl:"https://stadsring.nl/",orgType:"regionale schuldhulporganisatie"},
  {gemeente:"Barendrecht",url:"https://www.barendrecht.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Barneveld",url:"https://www.barneveld.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Beek",url:"https://www.beek.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Beekdaelen",url:"https://www.beekdaelen.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Beesel",url:"https://www.beesel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Berg en Dal",url:"https://www.bergendal.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Bergeijk",url:"https://www.bergeijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Bergen (NH)",url:"https://www.bergen-nh.nl/aanvragen-en-regelen/hulp-bij-schulden",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Bergen (L)",url:"https://www.bergen(l).nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Bergen op Zoom",url:"https://www.bergenopzoom.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Berkelland",url:"https://www.berkelland.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Bernheze",url:"https://www.bernheze.nl/schuldhulpverlening",partner:"GKB Den Bosch",partnerUrl:"https://www.s-hertogenbosch.nl/gkb"},
  {gemeente:"Best",url:"https://www.best.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Beuningen",url:"https://www.beuningen.nl/schuldhulpverlening",partner:"GKB Nijmegen",partnerUrl:"https://www.nijmegen.nl"},
  {gemeente:"Beverwijk",url:"https://www.beverwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Bladel",url:"https://www.bladel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Blaricum",url:"https://www.blaricum.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Bloemendaal",url:"https://www.bloemendaal.nl/hulp-bij-geldzaken-en-werk/hulp-bij-schulden-en-geldzorgen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"IASZ / Haarlem-route",orgUrl:"https://www.iasz.nl/hulp-bij-schulden/hulp-bij-schulden-voor-inwoners",orgType:"intergemeentelijke sociale dienst"},
  {gemeente:"Bodegraven-Reeuwijk",url:"https://www.bodegravenreeuwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Boekel",url:"https://www.boekel.nl/schuldhulpverlening",partner:"GKB Den Bosch",partnerUrl:"https://www.s-hertogenbosch.nl/gkb"},
  {gemeente:"Borger-Odoorn",url:"https://www.borgerodoorn.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Borne",url:"https://www.borne.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Borsele",url:"https://www.borsele.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Boxtel",url:"https://www.boxtel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Breda",url:"https://www.breda.nl/hulp-bij-geldzorgen-schulden",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl",orgName:"Kredietbank West-Brabant",orgUrl:"https://www.breda.nl/kredietbank",orgType:"kredietbank"},
  {gemeente:"Bronckhorst",url:"https://www.bronckhorst.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Brummen",url:"https://www.brummen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Brunssum",url:"https://www.brunssum.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Bunnik",url:"https://www.bunnik.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Bunschoten",url:"https://www.bunschoten.nl/schuldhulpverlening",partner:"Stadsring",partnerUrl:"https://stadsring.nl",orgName:"Stadsring",orgUrl:"https://stadsring.nl/",orgType:"regionale schuldhulporganisatie"},
  {gemeente:"Buren",url:"https://www.buren.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Capelle aan den IJssel",url:"https://www.capelleaandenijssel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Castricum",url:"https://www.castricum.nl/aanvragen-en-regelen/hulp-bij-schulden/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Coevorden",url:"https://www.coevorden.nl/schuldhulpverlening",partner:"Schulddienstverlening Emmen",partnerUrl:"https://www.emmen.nl"},
  {gemeente:"Culemborg",url:"https://www.culemborg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Dalfsen",url:"https://www.dalfsen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Dantumadiel",url:"https://www.dantumadiel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"De Bilt",url:"https://www.debilt.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"De Fryske Marren",url:"https://www.defryskemarren.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"De Ronde Venen",url:"https://www.derondevenen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"De Wolden",url:"https://www.dewolden.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Delft",url:"https://www.delft.nl/hulp-bij-schuld",partner:"Kredietbank Den Haag",partnerUrl:"https://www.denhaag.nl/kredietbank",orgName:"SchuldHulpMaatje Delft",orgUrl:"https://schuldhulpmaatje.nl/delft/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Den Haag",url:"https://www.denhaag.nl/nl/geld-en-schulden/uw-schulden-oplossen/",partner:"Kredietbank Den Haag",partnerUrl:"https://www.denhaag.nl/kredietbank",orgName:"SchuldHulpMaatje Den Haag",orgUrl:"https://schuldhulpmaatje.nl/den-haag/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Den Helder",url:"https://www.denhelder.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Deurne",url:"https://www.deurne.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Deventer",url:"https://www.deventer.nl/geld-en-inkomen/hulp-bij-geldzorgen-of-schulden",partner:"Kredietbank Salland",partnerUrl:"https://www.kredietbank-salland.nl",orgName:"Budget Adviesbureau Deventer (BAD)",orgUrl:"https://www.deventerwijzer.nl/is/een-vraag-over/werk-geld-en-uitkering/geldzaken/schulden/schuldhulpverlening",orgType:"gemeentelijke schuldhulp / budgetadvies"},
  {gemeente:"Diemen",url:"https://www.diemen.nl/schuldhulpverlening",partner:"Kredietbank Amsterdam",partnerUrl:"https://www.amsterdam.nl/schuldhulp"},
  {gemeente:"Dijk en Waard",url:"https://www.dijkenwaard.nl/zorg-werk-en-jeugd/inkomen-werk-en-schulden/schulden-en-geldzorgen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Dinkelland",url:"https://www.dinkelland.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Doesburg",url:"https://www.doesburg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Doetinchem",url:"https://www.doetinchem.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Dongen",url:"https://www.dongen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Dordrecht",url:"https://cms.dordrecht.nl/Inwoners/Overzicht_Inwoners/Zorg_en_ondersteuning/hulp_bij_geldzaken",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl",orgName:"Sociale Dienst Drechtsteden",orgUrl:"https://www.socialedienstdrechtsteden.nl/geldzorgen/ik-ben-inwoner/ik-zoek-hulp",orgType:"regionale sociale dienst"},
  {gemeente:"Drechterland",url:"https://www.drechterland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Drimmelen",url:"https://www.drimmelen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Dronten",url:"https://www.dronten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Druten",url:"https://www.druten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Duiven",url:"https://www.duiven.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Echt-Susteren",url:"https://www.echtsusteren.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Edam-Volendam",url:"https://www.edamvolendam.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Ede",url:"https://www.ede.nl/ondersteuning-werk-inkomen/hulp-bij-schulden-aanvragen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"SchuldHulpMaatje Ede",orgUrl:"https://schuldhulpmaatje.nl/ede/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Eemsdelta",url:"https://www.eemsdelta.nl/schuldhulpverlening",partner:"Volkskredietbank Noord-Oost Groningen",partnerUrl:"https://www.vkb.nl"},
  {gemeente:"Eemnes",url:"https://www.eemnes.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Eersel",url:"https://www.eersel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Eijsden-Margraten",url:"https://www.eijsdenmargraten.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Eindhoven",url:"https://www.eindhoven.nl/inkomen-zorg-en-onderwijs/inkomen/hulp-bij-geldzorgen/hulp-bij-schulden",partner:"Gemeente Eindhoven",partnerUrl:"https://www.wijeindhoven.nl",orgName:"Werkplaats Financiën",orgUrl:"https://werkplaatsfinancien.nl/hulp-nodig/",orgType:"lokale financiële hulp"},
  {gemeente:"Elburg",url:"https://www.elburg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Emmen",url:"https://www.emmen.nl/schuldhulpverlening",partner:"Schulddienstverlening Emmen",partnerUrl:"https://www.emmen.nl"},
  {gemeente:"Enkhuizen",url:"https://www.enkhuizen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Enschede",url:"https://www.enschede.nl/hulp-bij-schulden",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl",orgName:"Stadsbank Oost Nederland",orgUrl:"https://stadsbankoostnederland.nl/hulp-bij-geldzorgen/hulp-bij-schulden/",orgType:"stadsbank"},
  {gemeente:"Epe",url:"https://www.epe.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Ermelo",url:"https://www.ermelo.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Etten-Leur",url:"https://www.ettenleur.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Geertruidenberg",url:"https://www.geertruidenberg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Geldrop-Mierlo",url:"https://www.geldropmierlo.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Gemert-Bakel",url:"https://www.gemertbakel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Gennep",url:"https://www.gennep.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Gilze en Rijen",url:"https://www.gilzeenrijen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Goeree-Overflakkee",url:"https://www.goereeoverflakkee.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Goes",url:"https://www.goes.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Goirle",url:"https://www.goirle.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Gooise Meren",url:"https://www.gooisemeren.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Gorinchem",url:"https://www.gorinchem.nl/schuldhulpverlening",partner:"Avres",partnerUrl:"https://avres.nl"},
  {gemeente:"Gouda",url:"https://www.gouda.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Groningen",url:"https://gemeente.groningen.nl/hulp-bij-geldzaken-of-schulden",partner:"Groningse Kredietbank",partnerUrl:"https://gemeente.groningen.nl/gkb",orgName:"WIJ Groningen",orgUrl:"https://wij.groningen.nl/hulp-bij-thema/geld-werk/schulden/",orgType:"wijkteam / lokale hulp"},
  {gemeente:"Gulpen-Wittem",url:"https://www.gulpenwittem.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Haaksbergen",url:"https://www.haaksbergen.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Haarlem",url:"https://haarlem.nl/hulp-bij-geldzorgen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Schulddienstverlening Haarlem",orgUrl:"https://landelijk.socialekaartnederland.nl/organisaties/schulddienstverlening-haarlem",orgType:"gemeentelijke schulddienstverlening"},
  {gemeente:"Haarlemmermeer",url:"https://haarlemmermeergemeente.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"SchuldHulpMaatje Haarlemmermeer",orgUrl:"https://schuldhulpmaatje.nl/haarlemmermeer/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Halderberge",url:"https://www.halderberge.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Harderwijk",url:"https://www.harderwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hardinxveld-Giessendam",url:"https://www.hardinxveldgiessendam.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Harlingen",url:"https://www.harlingen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hattem",url:"https://www.hattem.nl/schuldhulpverlening",partner:"Gemeente Zwolle",partnerUrl:"https://www.zwolle.nl"},
  {gemeente:"Heemskerk",url:"https://www.heemskerk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Heemstede",url:"https://www.heemstede.nl/hulp-bij-geldzaken-en-werk/hulp-bij-schulden-en-geldzorgen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"IASZ / Haarlem-route",orgUrl:"https://www.iasz.nl/hulp-bij-schulden/hulp-bij-schulden-voor-inwoners",orgType:"intergemeentelijke sociale dienst"},
  {gemeente:"Heerde",url:"https://www.heerde.nl/schuldhulpverlening",partner:"Gemeente Zwolle",partnerUrl:"https://www.zwolle.nl"},
  {gemeente:"Heerenveen",url:"https://www.heerenveen.nl/schuldhulpverlening",partner:"Kredietbank Salland",partnerUrl:"https://www.kredietbank-salland.nl"},
  {gemeente:"Heeze-Leende",url:"https://www.heezeleende.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Heiloo",url:"https://www.heiloo.nl/aanvragen-en-regelen/hulp-bij-schulden/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Hellendoorn",url:"https://www.hellendoorn.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Helmond",url:"https://www.helmond.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hendrik-Ido-Ambacht",url:"https://www.hendrikidoambacht.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Hengelo",url:"https://www.hengelo.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Het Hogeland",url:"https://www.hethogeland.nl/schuldhulpverlening",partner:"Groningse Kredietbank",partnerUrl:"https://gemeente.groningen.nl/gkb"},
  {gemeente:"Heumen",url:"https://www.heumen.nl/schuldhulpverlening",partner:"GKB Nijmegen",partnerUrl:"https://www.nijmegen.nl"},
  {gemeente:"Heusden",url:"https://www.heusden.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hillegom",url:"https://www.hillegom.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hilvarenbeek",url:"https://www.hilvarenbeek.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hilversum",url:"https://www.hilversum.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hoeksche Waard",url:"https://www.hoekschewaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hof van Twente",url:"https://www.hofvantwente.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Hollands Kroon",url:"https://www.hollandskroon.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hoogeveen",url:"https://www.hoogeveen.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Hoorn",url:"https://www.hoorn.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Horst aan de Maas",url:"https://www.horstaandemaas.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Houten",url:"https://www.houten.nl/schuldhulpverlening",partner:"Gemeente Utrecht",partnerUrl:"https://www.u-centraal.nl"},
  {gemeente:"Huizen",url:"https://www.huizen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Hulst",url:"https://www.hulst.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"IJsselstein",url:"https://www.ijsselstein.nl/schuldhulpverlening",partner:"Gemeente Utrecht",partnerUrl:"https://www.u-centraal.nl"},
  {gemeente:"Kaag en Braassem",url:"https://www.kaagenbraassem.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Kampen",url:"https://www.kampen.nl/schuldhulpverlening",partner:"Kredietbank Salland",partnerUrl:"https://www.kredietbank-salland.nl"},
  {gemeente:"Kapelle",url:"https://www.kapelle.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Katwijk",url:"https://www.katwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Kerkrade",url:"https://www.kerkrade.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Koggenland",url:"https://www.koggenland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Krimpen aan den IJssel",url:"https://www.krimpenaandenijssel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Krimpenerwaard",url:"https://www.krimpenerwaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Laarbeek",url:"https://www.laarbeek.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Land van Cuijk",url:"https://www.landvancuijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Landgraaf",url:"https://www.landgraaf.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Landsmeer",url:"https://www.landsmeer.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Lansingerland",url:"https://www.lansingerland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Laren",url:"https://www.laren.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Leeuwarden",url:"https://www.leeuwarden.nl/hulp-bij-geldzorgen/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"SchuldHulpMaatje Leeuwarden",orgUrl:"https://schuldhulpmaatje.nl/leeuwarden/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Leiden",url:"https://gemeente.leiden.nl/inwoners-en-ondernemers/uitkering-en-inkomen/hulp-bij-schulden/schuldhulpverlening/",partner:"Stadsbank Leiden",partnerUrl:"https://www.leiden.nl",orgName:"Stadsbank Leiden",orgUrl:"https://voorzieningen.nl/organisatie/gemeente-leiden/schuldhulpverlening.html",orgType:"stadsbank / gemeentelijke uitvoering"},
  {gemeente:"Leiderdorp",url:"https://www.leiderdorp.nl/producten/schuldsanering",partner:"Stadsbank Leiden",partnerUrl:"https://www.leiden.nl",orgName:"Stadsbank Leiden",orgUrl:"https://voorzieningen.nl/organisatie/gemeente-leiden/schuldhulpverlening.html",orgType:"stadsbank / uitvoerende gemeentelijke dienst"},
  {gemeente:"Leidschendam-Voorburg",url:"https://www.leidschendamvoorburg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Lelystad",url:"https://www.lelystad.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Leudal",url:"https://www.leudal.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Leusden",url:"https://www.leusden.nl/rondkomen-1/hulp-bij-geldzorgen",partner:"Stadsring",partnerUrl:"https://stadsring.nl",orgName:"Stadsring",orgUrl:"https://stadsring.nl/",orgType:"regionale schuldhulporganisatie"},
  {gemeente:"Lingewaard",url:"https://www.lingewaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Lisse",url:"https://www.lisse.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Lochem",url:"https://www.lochem.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Loon op Zand",url:"https://www.loonopzand.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Lopik",url:"https://www.lopik.nl/schuldhulpverlening",partner:"Gemeente Utrecht",partnerUrl:"https://www.u-centraal.nl"},
  {gemeente:"Losser",url:"https://www.losser.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Maasdriel",url:"https://www.maasdriel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Maasgouw",url:"https://www.maasgouw.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Maashorst",url:"https://www.maashorst.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Maassluis",url:"https://www.maassluis.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Maastricht",url:"https://www.gemeentemaastricht.nl/teamvroegsignalering",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl",orgName:"Kredietbank Limburg",orgUrl:"https://www.socialezaken-mh.nl/hulp-bij-geldzorgen/kredietbank-limburg",orgType:"kredietbank"},
  {gemeente:"Medemblik",url:"https://www.medemblik.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Meerssen",url:"https://www.meerssen.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Meierijstad",url:"https://www.meierijstad.nl/schuldhulpverlening",partner:"GKB Den Bosch",partnerUrl:"https://www.s-hertogenbosch.nl/gkb"},
  {gemeente:"Meppel",url:"https://www.meppel.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Middelburg",url:"https://www.middelburg.nl/schuldhulpverlening",partner:"Orionis Walcheren",partnerUrl:"https://www.orioniswalcheren.nl"},
  {gemeente:"Midden-Delfland",url:"https://www.middendelfland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Midden-Drenthe",url:"https://www.middendrenthe.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Midden-Groningen",url:"https://www.middengroningen.nl/schuldhulpverlening",partner:"Kredietbank Midden-Groningen",partnerUrl:"https://www.midden-groningen.nl"},
  {gemeente:"Moerdijk",url:"https://www.moerdijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Molenlanden",url:"https://www.molenlanden.nl/schuldhulpverlening",partner:"Avres",partnerUrl:"https://avres.nl"},
  {gemeente:"Montferland",url:"https://www.montferland.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Montfoort",url:"https://www.montfoort.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Mook en Middelaar",url:"https://www.mookenmiddelaar.nl/schuldhulpverlening",partner:"GKB Nijmegen",partnerUrl:"https://www.nijmegen.nl"},
  {gemeente:"Neder-Betuwe",url:"https://www.nederbetuwe.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Nederweert",url:"https://www.nederweert.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Nieuwegein",url:"https://www.nieuwegein.nl/schuldhulpverlening",partner:"Gemeente Utrecht",partnerUrl:"https://www.u-centraal.nl"},
  {gemeente:"Nieuwkoop",url:"https://www.nieuwkoop.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Nijkerk",url:"https://www.nijkerk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Nijmegen",url:"https://www.nijmegen.nl/diensten/uitkering-schulden-laag-inkomen/hulp-bij-geldzorgen/",partner:"GKB Nijmegen",partnerUrl:"https://www.nijmegen.nl",orgName:"Bureau Schuldhulpverlening Nijmegen",orgUrl:"https://voorzieningen.nl/organisatie/bureau-schuldhulpverlening-nijmegen.html",orgType:"lokale schuldhulporganisatie / gemeentelijke dienst"},
  {gemeente:"Nissewaard",url:"https://www.nissewaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Noardeast-Fryslân",url:"https://www.noardeastfryslân.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Noord-Beveland",url:"https://www.noordbeveland.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Noordenveld",url:"https://www.noordenveld.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Noordoostpolder",url:"https://www.noordoostpolder.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Noordwijk",url:"https://www.noordwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Nuenen, Gerwen en Nederwetten",url:"https://www.nuenengerwenennederwetten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Nunspeet",url:"https://www.nunspeet.nl/schuldhulpverlening",partner:"Gemeente Zwolle",partnerUrl:"https://www.zwolle.nl"},
  {gemeente:"Oegstgeest",url:"https://www.oegstgeest.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oirschot",url:"https://www.oirschot.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oisterwijk",url:"https://www.oisterwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oldambt",url:"https://www.oldambt.nl/schuldhulpverlening",partner:"Volkskredietbank Noord-Oost Groningen",partnerUrl:"https://www.vkb.nl"},
  {gemeente:"Oldebroek",url:"https://www.oldebroek.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oldenzaal",url:"https://www.oldenzaal.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Olst-Wijhe",url:"https://www.olstwijhe.nl/schuldhulpverlening",partner:"Kredietbank Salland",partnerUrl:"https://www.kredietbank-salland.nl"},
  {gemeente:"Ommen",url:"https://www.ommen.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Oost Gelre",url:"https://www.oostgelre.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Oosterhout",url:"https://www.oosterhout.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Ooststellingwerf",url:"https://www.ooststellingwerf.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oostzaan",url:"https://www.oostzaan.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Opmeer",url:"https://www.opmeer.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Opsterland",url:"https://www.opsterland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oss",url:"https://www.oss.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oude IJsselstreek",url:"https://www.oudeijsselstreek.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Ouder-Amstel",url:"https://www.ouderamstel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Oudewater",url:"https://www.oudewater.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Overbetuwe",url:"https://www.overbetuwe.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Papendrecht",url:"https://www.papendrecht.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Peel en Maas",url:"https://www.peelenmaas.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Pekela",url:"https://www.pekela.nl/schuldhulpverlening",partner:"Volkskredietbank Noord-Oost Groningen",partnerUrl:"https://www.vkb.nl"},
  {gemeente:"Pijnacker-Nootdorp",url:"https://www.pijnackernootdorp.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Purmerend",url:"https://www.purmerend.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Putten",url:"https://www.putten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Raalte",url:"https://www.raalte.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Reimerswaal",url:"https://www.reimerswaal.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Renkum",url:"https://www.renkum.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Renswoude",url:"https://www.renswoude.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Reusel-De Mierden",url:"https://www.reuseldemierden.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Rheden",url:"https://www.rheden.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Rhenen",url:"https://www.rhenen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Ridderkerk",url:"https://www.ridderkerk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Rijssen-Holten",url:"https://www.rijssenholten.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Rijswijk",url:"https://www.rijswijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Roerdalen",url:"https://www.roerdalen.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Roermond",url:"https://www.roermond.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Roosendaal",url:"https://www.roosendaal.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Rotterdam",url:"https://www.rotterdam.nl/schuldhulpverlening-aanvragen",partner:"Nieuw Vaarwater (Rotterdam)",partnerUrl:"https://nieuwvaarwater.nl",orgName:"Nieuw Vaarwater",orgUrl:"https://nieuwvaarwater.nl/ik-zoek-hulp",orgType:"lokale schuldhulporganisatie"},
  {gemeente:"Rozendaal",url:"https://www.rozendaal.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Rucphen",url:"https://www.rucphen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Schagen",url:"https://www.schagen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Scherpenzeel",url:"https://www.scherpenzeel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Schiedam",url:"https://www.schiedam.nl/schuldhulpverlening",partner:"Nieuw Vaarwater (Rotterdam)",partnerUrl:"https://nieuwvaarwater.nl"},
  {gemeente:"Schiermonnikoog",url:"https://www.schiermonnikoog.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Schouwen-Duiveland",url:"https://www.schouwenduiveland.nl/schuldhulpverlening",partner:"Kredietbank Rotterdam",partnerUrl:"N/A"},
  {gemeente:"Simpelveld",url:"https://www.simpelveld.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Sint-Michielsgestel",url:"https://www.sintmichielsgestel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Sittard-Geleen",url:"https://www.sittardgeleen.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Sliedrecht",url:"https://www.sliedrecht.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Sluis",url:"https://www.sluis.nl/schuldhulpverlening",partner:"Kredietbank Rotterdam",partnerUrl:"N/A"},
  {gemeente:"Smallingerland",url:"https://www.smallingerland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Soest",url:"https://www.soest.nl/hulp-zorg-werk-en-inkomen/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Stadsring",orgUrl:"https://stadsring.nl/",orgType:"regionale schuldhulporganisatie"},
  {gemeente:"Someren",url:"https://www.someren.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Son en Breugel",url:"https://www.sonenbreugel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Stadskanaal",url:"https://www.stadskanaal.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Staphorst",url:"https://www.staphorst.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Stede Broec",url:"https://www.stedebroec.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Steenbergen",url:"https://www.steenbergen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Steenwijkerland",url:"https://www.steenwijkerland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Stein",url:"https://www.stein.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Stichtse Vecht",url:"https://www.stichtsevecht.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Terschelling",url:"https://www.terschelling.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Texel",url:"https://www.texel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Teylingen",url:"https://www.teylingen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Tholen",url:"https://www.tholen.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Tiel",url:"https://www.tiel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Tilburg",url:"https://www.tilburg.nl/inwoners/geldzorgen-en-schulden/hulp-bij-geldzorgen-en-schulden/",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl",orgName:"IMW Regio Tilburg",orgUrl:"https://www.imwregiotilburg.nl/voor-verwijzers/wat-we-doen/ondersteuning/financiele-hulpverlening",orgType:"maatschappelijk werk / financiële hulp"},
  {gemeente:"Tubbergen",url:"https://www.tubbergen.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Twenterand",url:"https://www.twenterand.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Tynaarlo",url:"https://www.tynaarlo.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Tytsjerksteradiel",url:"https://www.tytsjerksteradiel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Uitgeest",url:"https://www.uitgeest.nl/aanvragen-en-regelen/hulp-bij-schulden/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Zaffier",orgUrl:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",orgType:"regionale uitvoeringsorganisatie"},
  {gemeente:"Uithoorn",url:"https://www.uithoorn.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Urk",url:"https://www.urk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Utrecht",url:"https://www.utrecht.nl/werk-en-inkomen/geld-en-hulp-bij-rondkomen/hulp-bij-geldzorgen-en-schulden",partner:"Gemeente Utrecht",partnerUrl:"https://www.u-centraal.nl",orgName:"Buurtteams Utrecht",orgUrl:"https://www.buurtteamsutrecht.nl/onderwerp/geldzaken/schulden/",orgType:"buurtteam / lokale hulp"},
  {gemeente:"Utrechtse Heuvelrug",url:"https://www.utrechtseheuvelrug.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Vaals",url:"https://www.vaals.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Valkenburg aan de Geul",url:"https://www.valkenburgaandegeul.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Valkenswaard",url:"https://www.valkenswaard.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Veendam",url:"https://www.veendam.nl/schuldhulpverlening",partner:"Volkskredietbank Noord-Oost Groningen",partnerUrl:"https://www.vkb.nl"},
  {gemeente:"Veenendaal",url:"https://www.veenendaal.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Veere",url:"https://www.veere.nl/schuldhulpverlening",partner:"Orionis Walcheren",partnerUrl:"https://www.orioniswalcheren.nl"},
  {gemeente:"Veldhoven",url:"https://www.veldhoven.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Velsen",url:"https://www.velsen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Venlo",url:"https://www.venlo.nl/hulp-bij-schulden",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"SchuldHulpMaatje Venlo",orgUrl:"https://schuldhulpmaatje.nl/venlo/",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Venray",url:"https://www.venray.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Vijfheerenlanden",url:"https://www.vijfheerenlanden.nl/schuldhulpverlening",partner:"Avres",partnerUrl:"https://avres.nl"},
  {gemeente:"Vlaardingen",url:"https://www.vlaardingen.nl/schuldhulpverlening",partner:"Nieuw Vaarwater (Rotterdam)",partnerUrl:"https://nieuwvaarwater.nl"},
  {gemeente:"Vlieland",url:"https://www.vlieland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Vlissingen",url:"https://www.vlissingen.nl/schuldhulpverlening",partner:"Orionis Walcheren",partnerUrl:"https://www.orioniswalcheren.nl"},
  {gemeente:"Voerendaal",url:"https://www.voerendaal.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Voorne aan Zee",url:"https://www.voorneaanzee.nl/schuldhulpverlening",partner:"Kredietbank Rotterdam",partnerUrl:"N/A"},
  {gemeente:"Voorst",url:"https://www.voorst.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Voorschoten",url:"https://www.voorschoten.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Vught",url:"https://www.vught.nl/schuldhulpverlening",partner:"GKB Den Bosch",partnerUrl:"https://www.s-hertogenbosch.nl/gkb"},
  {gemeente:"Waadhoeke",url:"https://www.waadhoeke.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Waalre",url:"https://www.waalre.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"Waalwijk",url:"https://www.waalwijk.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Waddinxveen",url:"https://www.waddinxveen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Wageningen",url:"https://www.wageningen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Wassenaar",url:"https://www.wassenaar.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Waterland",url:"https://www.waterland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Weert",url:"https://www.weert.nl/schuldhulpverlening",partner:"Kredietbank Limburg",partnerUrl:"https://kredietbanklimburg.nl"},
  {gemeente:"West Betuwe",url:"https://www.westbetuwe.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"West Maas en Waal",url:"https://www.westmaasenwaal.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Westerkwartier",url:"https://www.westerkwartier.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Westerveld",url:"https://www.westerveld.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Westervoort",url:"https://www.westervoort.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Westerwolde",url:"https://www.westerwolde.nl/schuldhulpverlening",partner:"GKB Drenthe",partnerUrl:"https://www.degkb.nl"},
  {gemeente:"Weststellingwerf",url:"https://www.weststellingwerf.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Wierden",url:"https://www.wierden.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Wijchen",url:"https://www.wijchen.nl/schuldhulpverlening",partner:"GKB Nijmegen",partnerUrl:"https://www.nijmegen.nl"},
  {gemeente:"Wijdemeren",url:"https://www.wijdemeren.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Wijk bij Duurstede",url:"https://www.wijkbijduurstede.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Winterswijk",url:"https://www.winterswijk.nl/schuldhulpverlening",partner:"Stadsbank Oost Nederland",partnerUrl:"https://son.nl"},
  {gemeente:"Woensdrecht",url:"https://www.woensdrecht.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Woerden",url:"https://www.woerden.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Wormerland",url:"https://www.wormerland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Woudenberg",url:"https://www.woudenberg.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zaanstad",url:"https://www.zaanstad.nl/direct-regelen/werk-geld/uitkeringen/geldvragen-hulp-bij-schulden/",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Geldfit Zaanstad",orgUrl:"https://geldfitzaanstad.nl/",orgType:"lokaal spreekuur / samenwerkingsplatform"},
  {gemeente:"Zaltbommel",url:"https://www.zaltbommel.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zandvoort",url:"https://zandvoort.nl/hulp-bij-geldzorgen",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"Sociaal Wijkteam Haarlem/Zandvoort",orgUrl:"https://cjgkennemerland.nl/hulp-bij-schulden/",orgType:"wijkteam / lokale route"},
  {gemeente:"Zeewolde",url:"https://www.zeewolde.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zeist",url:"https://www.zeist.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zevenaar",url:"https://www.zevenaar.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zoetermeer",url:"https://www.zoetermeer.nl/hulp-bij-geldzaken-en-schulden",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl",orgName:"SchuldHulpMaatje Zoetermeer",orgUrl:"https://www.zoetermeerwijzer.nl/is/organisatie/144881/invis2/schuldhulpmaatje-zoetermeer",orgType:"vrijwillige lokale schuldhulp"},
  {gemeente:"Zoeterwoude",url:"https://www.zoeterwoude.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zuidplas",url:"https://www.zuidplas.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zundert",url:"https://www.zundert.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zutphen",url:"https://www.zutphen.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zwartewaterland",url:"https://www.zwartewaterland.nl/schuldhulpverlening",partner:"Kredietbank Nederland",partnerUrl:"https://kredietbanknederland.nl"},
  {gemeente:"Zwijndrecht",url:"https://www.zwijndrecht.nl/schuldhulpverlening",partner:"Kredietbank West-Brabant",partnerUrl:"https://kredietbankwestbrabant.breda.nl"},
  {gemeente:"Zwolle",url:"https://www.zwolle.nl/geldproblemen-oplossen",partner:"Gemeente Zwolle",partnerUrl:"https://www.zwolle.nl",orgName:"Eerste Hulp Bij Geldzaken Zwolle",orgUrl:"https://www.zwolle.nl/eerste-hulp-bij-geldzaken",orgType:"lokale gemeentelijke hulp"},
];

export interface Advocaat { name: string; url: string; }

export const ADVOCATEN_DATA: Record<string, Advocaat[]> = {
  "'s-Hertogenbosch": [{name:"Holla legal & tax",url:"https://www.holla.nl"},{name:"Banning Advocaten",url:"https://www.banning.nl"},{name:"AKD",url:"https://www.akd.eu"},{name:"LXA Legal",url:"https://www.lxa.nl"},{name:"Boels Zanders",url:"https://www.boelszanders.nl"}],
  "Alkmaar": [{name:"Schenkeveld Advocaten",url:"https://www.schenkeveldadvocaten.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"JENS Advocaten",url:"https://www.jensadvocaten.nl"},{name:"Advocatenkantoor Alkmaar",url:"https://www.advocatenkantooralkmaar.nl"},{name:"Onyx Advocaten",url:"https://www.onyx-advocaten.nl"}],
  "Almere": [{name:"Okkerse & Schop",url:"https://www.okkerse-schop.nl"},{name:"PVM Advocaten",url:"https://www.pvm.nl"},{name:"Claassen Advocaten",url:"https://www.claassenadvocaten.nl"},{name:"Advocatenkantoor Almere",url:"https://www.advocatenkantooralmere.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"}],
  "Alphen aan den Rijn": [{name:"Berntsen Mulder",url:"https://www.berntsenmulder.nl"},{name:"Kroes Advocaten",url:"https://www.kroesadvocaten.nl"},{name:"TeekensKarstens",url:"https://www.tk.nl"},{name:"Just Advocaten",url:"https://www.justadvocaten.nl"},{name:"De Clercq",url:"https://www.declercq.com"}],
  "Amersfoort": [{name:"Van Benthem & Keulen",url:"https://www.vbk.nl"},{name:"CMS",url:"https://www.cms.law"},{name:"Nysingh",url:"https://www.nysingh.nl"},{name:"Schipper en de Jonge",url:"https://www.schipperen dejonge.nl"},{name:"Boels Zanders",url:"https://www.boelszanders.nl"}],
  "Amsterdam": [{name:"De Brauw Blackstone Westbroek",url:"https://www.debrauw.com"},{name:"NautaDutilh",url:"https://www.nautadutilh.com"},{name:"Stibbe",url:"https://www.stibbe.com"},{name:"Houthoff",url:"https://www.houthoff.com"},{name:"Loyens & Loeff",url:"https://www.loyensloeff.com"}],
  "Apeldoorn": [{name:"JPR Advocaten",url:"https://www.jpr.nl"},{name:"Nysingh",url:"https://www.nysingh.nl"},{name:"Bastide Advocaten",url:"https://www.bastide.nl"},{name:"Berendsen Advocaten",url:"https://www.berendsenadvocaten.nl"},{name:"Cleerdin & Hamer",url:"https://www.cleerdin-hamer.nl"}],
  "Arnhem": [{name:"Dirkzwager",url:"https://www.dirkzwager.nl"},{name:"Hekkelman",url:"https://www.hekkelman.nl"},{name:"Nysingh",url:"https://www.nysingh.nl"},{name:"CMS",url:"https://www.cms.law"},{name:"Stellicher",url:"https://www.stellicher.nl"}],
  "Breda": [{name:"Ruitenberg Advocaten",url:"https://www.ruitenberg.com"},{name:"Van Iersel Luchtman",url:"https://www.vil.nl"},{name:"Snijders Advocaten",url:"https://www.snijders-advocaten.nl"},{name:"De Vos & Partners",url:"https://www.devos.nl"},{name:"Taylor Wessing",url:"https://www.taylorwessing.com"}],
  "Delft": [{name:"GMW Advocaten",url:"https://www.gmw.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"Westland Partners",url:"https://www.westlandpartners.nl"},{name:"Buren",url:"https://www.burenlegal.com"},{name:"DVDW Advocaten",url:"https://www.dvdw.nl"}],
  "Den Haag": [{name:"Pels Rijcken",url:"https://www.pelsrijcken.nl"},{name:"BarentsKrans",url:"https://www.barentskrans.nl"},{name:"Bird & Bird",url:"https://www.twobirds.com"},{name:"Delissen Martens",url:"https://www.delissenmartens.nl"},{name:"GMW Advocaten",url:"https://www.gmw.nl"}],
  "Dordrecht": [{name:"Ten Holter Noordam",url:"https://www.thna.nl"},{name:"Visser Advocaten",url:"https://www.visseradvocaten.nl"},{name:"DVDW Advocaten",url:"https://www.dvdw.nl"},{name:"Westland Partners",url:"https://www.westlandpartners.nl"},{name:"Hoogendoorn Advocaten",url:"https://www.hoogendoornadvocaten.nl"}],
  "Ede": [{name:"Van Veen Advocaten",url:"https://www.vanveen.nl"},{name:"Berendsen Advocaten",url:"https://www.berendsenadvocaten.nl"},{name:"JPR Advocaten",url:"https://www.jpr.nl"},{name:"Dirkzwager",url:"https://www.dirkzwager.nl"},{name:"Nysingh",url:"https://www.nysingh.nl"}],
  "Eindhoven": [{name:"Holla legal & tax",url:"https://www.holla.nl"},{name:"Boels Zanders",url:"https://www.boelszanders.nl"},{name:"Taylor Wessing",url:"https://www.taylorwessing.com"},{name:"Dirkzwager",url:"https://www.dirkzwager.nl"},{name:"AKD",url:"https://www.akd.eu"}],
  "Emmen": [{name:"Benthem Gratama",url:"https://www.benthemgratama.nl"},{name:"Trip Advocaten",url:"https://www.trip.nl"},{name:"Dommerholt Advocaten",url:"https://www.dommerholt.nl"},{name:"De Haan Advocaten",url:"https://www.dehaanlaw.com"},{name:"Vechtstede Notarissen",url:"https://www.vechtstede.nl"}],
  "Enschede": [{name:"Damsté",url:"https://www.damste.nl"},{name:"KienhuisHoving",url:"https://www.kienhuishoving.nl"},{name:"JPR Advocaten",url:"https://www.jpr.nl"},{name:"Benthem Gratama",url:"https://www.benthemgratama.nl"},{name:"Huver Advocaten",url:"https://www.huveradvocaten.nl"}],
  "Groningen": [{name:"Trip Advocaten",url:"https://www.trip.nl"},{name:"PlasBossinade",url:"https://www.plasbossinade.nl"},{name:"De Haan Advocaten",url:"https://www.dehaanlaw.com"},{name:"Bout Advocaten",url:"https://www.boutadvocaten.nl"},{name:"Yspeert Advocaten",url:"https://www.yspeert.nl"}],
  "Haarlem": [{name:"Pot Jonker",url:"https://www.potjonker.nl"},{name:"TeekensKarstens",url:"https://www.tk.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"Buren",url:"https://www.burenlegal.com"},{name:"Schenkeveld Advocaten",url:"https://www.schenkeveldadvocaten.nl"}],
  "Haarlemmermeer": [{name:"Schenkeveld Advocaten",url:"https://www.schenkeveldadvocaten.nl"},{name:"LXA Legal",url:"https://www.lxa.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"Lexence",url:"https://www.lexence.com"},{name:"Taylor Wessing",url:"https://www.taylorwessing.com"}],
  "Leeuwarden": [{name:"Trip Advocaten",url:"https://www.trip.nl"},{name:"Rotshuizen Geense",url:"https://www.rotshuizengeense.nl"},{name:"De Haan Advocaten",url:"https://www.dehaanlaw.com"},{name:"PlasBossinade",url:"https://www.plasbossinade.nl"},{name:"Schenkeveld Advocaten",url:"https://www.schenkeveldadvocaten.nl"}],
  "Leiden": [{name:"RWV Advocaten",url:"https://www.rwv.nl"},{name:"TeekensKarstens",url:"https://www.tk.nl"},{name:"MenD",url:"https://www.mend.nl"},{name:"De Clercq",url:"https://www.declercq.com"},{name:"Zumpolle Advocaten",url:"https://www.zumpolleadfocaten.nl"}],
  "Maastricht": [{name:"Boels Zanders",url:"https://www.boelszanders.nl"},{name:"Thuis Partners",url:"https://www.thuispartners.nl"},{name:"Paulussen Advocaten",url:"https://www.paulussen.nl"},{name:"Spee Advocaten",url:"https://www.speeadvocaten.nl"},{name:"LXA Legal",url:"https://www.lxa.nl"}],
  "Nijmegen": [{name:"Poelmann van den Broek",url:"https://www.pvdb.nl"},{name:"Hekkelman",url:"https://www.hekkelman.nl"},{name:"Dirkzwager",url:"https://www.dirkzwager.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"Beks Advocaten",url:"https://www.beksadvocaten.nl"}],
  "Rotterdam": [{name:"AKD",url:"https://www.akd.eu"},{name:"Ploum",url:"https://www.ploum.nl"},{name:"Kneppelhout",url:"https://www.kneppelhout.nl"},{name:"Schaap Advocaten",url:"https://www.schaap.eu"},{name:"Lexys Advocaten",url:"https://lexysadvocaten.nl/"}],
  "Tilburg": [{name:"MannaertsAppels",url:"https://www.mannaertsappels.nl"},{name:"Van Iersel Luchtman",url:"https://www.vil.nl"},{name:"De Voort",url:"https://www.devoort.nl"},{name:"Asselbergs & Klinkhamer",url:"https://www.ak-advocaten.nl"},{name:"Linssen Advocaten",url:"https://www.linssen-advocaten.nl"}],
  "Utrecht": [{name:"Van Benthem & Keulen",url:"https://www.vbk.nl"},{name:"CMS",url:"https://www.cms.law"},{name:"Wijn & Stael",url:"https://www.wijnstael.nl"},{name:"Nysingh",url:"https://www.nysingh.nl"},{name:"Derks Star Busmann (CMS)",url:"https://cms.law/nl/nld/"}],
  "Westland": [{name:"Westland Partners",url:"https://www.westlandpartners.nl"},{name:"GMW Advocaten",url:"https://www.gmw.nl"},{name:"RWV Advocaten",url:"https://www.rwv.nl"},{name:"Just Advocaten",url:"https://www.justadvocaten.nl"},{name:"DVDW Advocaten",url:"https://www.dvdw.nl"}],
  "Zaanstad": [{name:"Abma Schreurs",url:"https://www.abmaschreurs.nl"},{name:"Zaanse Meesters",url:"https://www.zaansemeesters.nl"},{name:"Van Diepen Van der Kroef",url:"https://www.vandiepen.com"},{name:"Swart Legal",url:"https://www.swartlegal.nl"},{name:"KB Advocaten",url:"https://www.kbadvocaten.nl"}],
  "Zoetermeer": [{name:"GMW Advocaten",url:"https://www.gmw.nl"},{name:"RWV Advocaten",url:"https://www.rwv.nl"},{name:"Just Advocaten",url:"https://www.justadvocaten.nl"},{name:"Buntsma Advocaten",url:"https://www.buntsma-advocaten.nl"},{name:"Bos Advocaten",url:"https://www.bosadvocaten.nl"}],
  "Zwolle": [{name:"Nysingh",url:"https://www.nysingh.nl"},{name:"Benthem Gratama",url:"https://www.benthemgratama.nl"},{name:"Dommerholt Advocaten",url:"https://www.dommerholt.nl"},{name:"KienhuisHoving",url:"https://www.kienhuishoving.nl"},{name:"IJssel Advocaten",url:"https://www.ijsseladvocaten.nl"}],
};

export const MULTI_GEMEENTE_ORGS = [
  {name:"Stadsring",url:"https://stadsring.nl/",coverage:"Amersfoort; Baarn; Bunschoten; Leusden; Soest; Woudenberg"},
  {name:"Zaffier",url:"https://www.zaffier.nl/geldzaken/hulp-bij-schulden/ik-heb-schulden-en-wil-hulp/",coverage:"Alkmaar; Bergen (NH); Castricum; Dijk en Waard; Heiloo; Uitgeest"},
  {name:"Stadsbank Leiden",url:"https://voorzieningen.nl/organisatie/gemeente-leiden/schuldhulpverlening.html",coverage:"Leiden; Leiderdorp"},
  {name:"Schulddienstverlening Haarlem / Haarlem-route",url:"https://haarlem.nl/hulp-bij-geldzorgen",coverage:"Haarlem; Bloemendaal; Heemstede; Zandvoort"},
  {name:"Verder",url:"https://www.verdergroep.nl/schuldhulpverlening-aanvragen/",coverage:"Almere; Haarlemmermeer"},
  {name:"Kredietbank Limburg",url:"https://www.socialezaken-mh.nl/hulp-bij-geldzorgen/kredietbank-limburg",coverage:"Maastricht; meerdere Limburgse gemeenten"},
  {name:"Stadsbank Oost Nederland",url:"https://stadsbankoostnederland.nl/",coverage:"Enschede; meerdere Twentse en Achterhoekse gemeenten"},
];

/** Find gemeente data by name (case-insensitive) */
export function findGemeente(name: string): GemeenteData | undefined {
  const lower = name.toLowerCase();
  return GEMEENTE_DATA.find((g) => g.gemeente.toLowerCase() === lower);
}

/** Find advocaten for a city */
export function findAdvocaten(city: string): Advocaat[] {
  return ADVOCATEN_DATA[city] || [];
}

/** Get all gemeente names for search */
export const ALL_GEMEENTE_NAMES = GEMEENTE_DATA.map((g) => g.gemeente);